### ISSUE TITLE
Add Madeira (PT)

### ISSUE THREAD

**Issue by alixunderplatz** [electricitymap/electricitymap-contrib#1055]
There is data for Madeira's generation mix from "Empresa de Electricidade da Madeira, S. A.":
https://www.eem.pt/pt/graficos/

![image](https://user-images.githubusercontent.com/25743609/35674105-e81bb634-0743-11e8-9759-4d7f8b849ada.png)

Data is only published for "d-2" and not in real-time in the format of an image, so we can not extract anything at the moment. 
As @systemcatch suggested on Slack, we should contact them and ask for another data format like csv / JSON / ... and if there are any constraints that prevent publishing it as live-data.

Here are contacts from their site:
Customer support: clientes@eem.pt
IT (?)/technical support: pit_at@eem.pt

**Comment by jarek** [comment]
This also seems like it would be a good fit for the "Standard api for data providers" idea in #1232

**Comment by corradio** [comment]
Has anyone contacted them?

**Comment by alixunderplatz** [comment]
@corradio I didn't

**Comment by systemcatch** [comment]
I'll try emailing them, @corradio do you want me to mention/link the EM or leave that out for now?

**Comment by corradio** [comment]
Feel free to mention the EM. It tends to help :)

**Comment by jarek** [comment]
Removing "help wanted" as for the time we have no data to integrate

**Comment by brandongalbraith** [comment]
Is this a matter of someone doing the research of making contact to suss
out a data source? Seeking context to contribute on this issue if possible.

**Comment by jarek** [comment]
Basically, we'd need the system operator (EEM here I guess) to provide computer-readable data in addition to the generated image. CSV, XML, JSON, whatever is most convenient for them. @alixunderplatz posted an email address in the first post and @systemcatch said he wrote to them, but I guess they never heard back, or nothing that we can use. It can be tough to get the message to the right technical person at the organization, let alone get the organization to change their systems.

Alternatively, write a mad hack that OCRs the image to get axis values and then looks at the image pixel by pixel and parses the colour of each pixel to find the values for each fuel ;) (The [Aland Islands parser](https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/AX.py) does something not entirely unlike that... but it does get live data, so it's more satisfying)

**Comment by systemcatch** [comment]
Yeah I never heard back from them, probably need something better than google translated Portuguese.

It's annoying as that graph is likely generated from an excel file.

**Comment by brandongalbraith** [comment]
Emailed the author of [Energy storage for renewable energy integration: the case of
Madeira Island, Portugal](https://ac.els-cdn.com/S187661021735227X/1-s2.0-S187661021735227X-main.pdf?_tid=46cc2cd0-6523-4ca7-ace2-15715503e774&acdnat=1551819483_cebc71474e0ce00498566bb797b244bc) who has collaborated with EEM in hopes they're able to provide a technical contact for generation data.

**Comment by alixunderplatz** [comment]
@brandongalbraith Did you ever get a response from the person you had contaced regarding data for Madeira?

**Comment by brandongalbraith** [comment]
@alixunderplatz Unfortunately not.

**Comment by alixunderplatz** [comment]
@brandongalbraith ok then I'll try to contact someone working for a Portugese renewables project developer ;)

**Comment by Kongkille** [comment]
Thanks for all the valuable information shared here! 🙌

We're closing this issue and adding to our main issue for missing countries as it doesn't currently seem possible to build a real-time parser given the data provided here.
If you find new information that might help us get it done, please comment and reopen the issue [when a parser is buildable](https://github.com/electricityMap/electricitymap-contrib/wiki/Technical-requirements-for-parser-data)

It seems the website is still up and running 4 years later, so they likely have some very valuable data if we can get in contact with them :)

**Comment by q--** [comment]
Looks like the graph is now gone from the website. The contact e-mail address is still the same, if anyone wants to ask them if they intent to put it back. (By the way, the pit_at one seems to have been for help with grid connection issues and is no longer listed in the website footer, [clientes@eem.pt](mailto:clientes@eem.pt) is still mentioned.)
