### ISSUE TITLE
Regional data for UK / GB

### ISSUE THREAD

**Issue by corradio** [electricitymap/electricitymap-contrib#1894]
https://carbonintensity.org.uk/ has regional breakdown that we might be able to use.
We need to have api access and get access to:
- power production breakdown
- imports between each areas
- geojson (https://s3.eu-west-2.amazonaws.com/carbonintensity.org.uk/DNORegions_pretty_test_country.geojson)

**Comment by jarek** [comment]
Their calculations seem to produce unusual results, they're showing London as 97 gCOeq with 92% gas while East England is 287 g with 73% gas...

![image](https://user-images.githubusercontent.com/47415/60130933-34cfc200-9766-11e9-9cf8-fda802266dda.png)

![image](https://user-images.githubusercontent.com/47415/60130973-4fa23680-9766-11e9-95db-d3f542235730.png)

**Comment by systemcatch** [comment]
This is all forecasted data right?

API docs - https://api.carbonintensity.org.uk/

It seems like no auth is needed for the API.

**Comment by ABerrow** [comment]
Hey there, i was passing by, saw these comments and i have been looking at that website for a while now, the numbers seem fairly accurate when it comes to generation. I have been comparing the generation numbers with another website and they are fairly close. For refinement of solar generation this may help https://www.solar.sheffield.ac.uk/pvlive/ . This http://grid.iamkate.com/  is also another one that i have been looking at for a while which may also help, but i cant find anything for individual areas.

**Comment by AyrtonB** [comment]
@systemcatch They provide both forecasted and historic data

possibly helpful functions for the parser in here - https://github.com/AyrtonB/NG-Carbon-Intensity/blob/master/Emissions%20Scraper%20Walkthrough.ipynb

**Comment by peterhughgriffin** [comment]
> https://carbonintensity.org.uk/ has regional breakdown that we might be able to use.
> We need to have api access and get access to:
> 
> * power production breakdown
> * imports between each areas

I don't think it's too simple to do either of these things.

Firstly, it gives all the power production as percentage of total, I can't find any way to get at MW values. Integrating percentages would require cross referencing with total production from Elexon, which seems rather over complicated. Secondly, the regional data has an estimate of the proportion of coal/wind/imports etc, but does not show energy flows between the regions.

I've [asked on their github](https://github.com/carbon-intensity/api-definitions/issues/4) whether getting either of these might be possible, but they are not particularly active on there, so not sure how quick a response might be.

The methodology for regional work is here: https://github.com/carbon-intensity/methodology/raw/master/Regional%20Carbon%20Intensity%20Forecast%20Methodology.pdf

**Comment by AyrtonB** [comment]
Yeah its a shame theres no figure for demand in MW by region.

If you want to scrape the data I put some code together to do it a while back - https://github.com/AyrtonB/NG-Carbon-Intensity/blob/master/Emissions%20Scraper%20Walkthrough.ipynb

**Comment by AyrtonB** [comment]
And looks like the GeoJSON can be downloaded from here - https://s3.eu-west-2.amazonaws.com/carbonintensity.org.uk/DNORegions_pretty_test_country.geojson

**Comment by corradio** [comment]
FYI, @robertahunt and I were in touch with National Grid about this. @robertahunt did you receive an update from them?

**Comment by robertahunt** [comment]
Not in the last couple months. Last I heard they sounded positive about releasing the data publicly, but I would guess their internal processes to finalize this take some time. I'll send them a mail asking for an update.

**Comment by robertahunt** [comment]
I got a prompt response! Sounds like they are close to releasing an upgraded version of the site with regional flow. No exact date, but we should keep an eye out for it.

**Comment by corradio** [comment]
Note: https://github.com/tmrowco/electricitymap-contrib/issues/2696 had a lot of very good input on this matter.

**Comment by corradio** [comment]
I've reached out to National grid to ask for a production version of their interconnector endpoint

**Comment by corradio** [comment]
Update: I've talked to National Grid and they might have a production version of the API ready this summer.
We have decided not to use their beta version for now, as it seems that a lot of data is estimated and it might not completely reflect reality.

**Comment by Kongkille** [comment]
I'm adding this to our main issue for missing data. Please reopen, if we believe the data has been improved :)

**Comment by danuw** [comment]
Hi @corradio, how about now (2 years later), does the data look better please? Would be great to get more granularity of the data for UK regions but it does not look like the linked issue has been answered on their side.

**Comment by corradio** [comment]
Hello @danuw ,

I'm now less involved in the technical aspects here, but I suggest you follow https://github.com/electricitymaps/electricitymaps-contrib/issues/4735 as this seems to be the place where the discussion will happen.

I'd also love more granularity here :)
