### ISSUE TITLE
Fix regional parsers for India (IN)

### ISSUE THREAD

**Issue by alixunderplatz** [electricitymap/electricitymap-contrib#1982]
We used to have working parsers for electricity production of 8 States of India
(see https://github.com/tmrowco/electricitymap-contrib/tree/master/parsers IN-....py).

Recently, only 2-3 of the indian parsers still work, so the others need a check / fix. Maybe it's just the format, or sometimes the website or the url doesn't exist anymore. 

We used to have issues regarding Indian states in the electricitymap repo in the past, so use the searchbar for maximum amount of details 😉 #304 is the general issue for India

When searching the web for any Indian regional data, these terms will help:
"[name of state] **S**tate **L**oad **D**espatch **C**entre"
If you're on one of the SLDC websites, look out for the term "real-time data", there you'll find either production per type or per power plant.

These parsers need a check / fix:

IN-AP (Andhra Pradesh)
----------
Data-URL for parser is working, but the timestamp and the data are stuck:
https://core.ap.gov.in/CMDashBoard/UserInterface/Power/PowerReport.aspx
Check/Watch if the timestamp is stuck or the entire production data.

IN-CT (Chhattisgarh)
-----------
Data-URL for parser is actually working:
http://117.239.199.203/csptcl/GEN.aspx
I guess the code needs to be adjusted, so the data will be parsed correctly.

IN-GJ (Gujarat)
-----------
The website of the SLDC doesn't exist anymore. Is there a new website with the desired data somewhere?

IN-KA (Karnataka)
-----------
Working, but the data is unreliable (nothing we can change).

IN-PB (Punjab)
-----------
URLs probably have changed to:
http://www.punjabsldc.org/realtimepbGen.aspx 
for conventional production
and
http://www.punjabsldc.org/realtimeresgen.aspx
for renewable production. The last site was not loading when I checked, unfortunately...

IN-UT (Uttarakhand)
-----------
URL is working, but data has been showing "0 MW" for a long time (nothing we can do about it).
http://uksldc.in/real-time-data.php

**Comment by KyleARector** [comment]
Would it be alright if I picked this issue up?

**Comment by systemcatch** [comment]
@martincollignon, @alixunderplatz I propose we switch India back to using the whole country parser (https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/IN.py) for now, there are too many errors in the regional parsers.

**Comment by alixunderplatz** [comment]
@systemcatch agreed. India's electricity production is really complicated, anyway (independent producers, state producers, shared power plants, ...), so I think data-wise it's the safest to "reduce" to the whole country.

**Comment by alixunderplatz** [comment]
@kyleARector from the list above, I think Chattisgarh / IN-CT.py is something that seems fixable :) 
Go ahead if you like!

**Comment by systemcatch** [comment]
I will redo the Punjab parser to work with the new urls.

**Comment by alixunderplatz** [comment]
@systemcatch here we go:
From the first page you can actually grab all the data.
http://www.punjabsldc.org/realtimepbGen.aspx
"Total Thermal" and "Total Ipps" as "coal" (like in the existing parser)
"Total Hydro" as "hydro"
"Solar" as "solar" (also active at night due to concentrated solar power)
"NON-Solar" as "biomass" and were done :)

**Comment by srinathjayaraman** [comment]
I was looking at this issue and I think I figured out where SLDC for Gujarat went - I think the site is now https://www.getcogujarat.com/getco_new/pages/introduction.php

I am not 100% sure but I think it's a good start.

**Comment by Kongkille** [comment]
It seems that most of these URLs aren't valid. To keep the issue a bit more focused, I suggest we open new issues separately for the regions where there is data we can add :)
