### ISSUE TITLE
Data for Pakistan

### ISSUE THREAD

**Issue by UPstartDeveloper** [electricitymap/electricitymap-contrib#2034]
We haven't found the data for this region yet, but that doesn't mean you can't make it happen!

Ranked from best to useful information, here is what we could use:
- real-time data of energy generation by energy source
- historical data of energy generation by energy source (as recent and as granular as possible)
- contact details (contact form, email or social media) of someone who may have access to that data
- contact details (contact form, email or social media) of an organisation which may have access to that data

**Comment by UPstartDeveloper** [comment]
Thanks to whoever wrote the text for the previous comment!

**Comment by UPstartDeveloper** [comment]
Here is a list of data sources I think may be helpful. It looks like we may be able to build a parser for Pakistan!
https://energypedia.info/wiki/Pakistan_Energy_Situation 
https://www.ceicdata.com/en/pakistan/energy-consumption-and-supplies-annual
https://www.ceicdata.com/en/indicator/pakistan/electricity-production
https://www.indexmundi.com/g/g.aspx?c=pk&v=81
https://tradingeconomics.com/pakistan/electricity-production
https://www.worlddata.info/asia/pakistan/energy-consumption.php

**Comment by UPstartDeveloper** [comment]
So far I have not been able to find any real-time data on how Pakistan generates its energy, or by which energy source its energy is coming from. 

For historical data, the CEIC website looks somewhat promising, but it's not very granular: https://www.ceicdata.com/en/indicator/pakistan/electricity-production. They have data on Pakistan's electricity production from for every calendar month between April 2018-March 2019. The website above DOES NOT break down the energy generation by source however. For example, data on coal and natural gas production are found on separate pages. 

Records go back as November 1987.

**Comment by UPstartDeveloper** [comment]
As for an organization/person that could help, I think our best bet is the Government of Pakistan's (sometimes abbreviated GOP) Ministry of Energy (Power Division) http://www.mowp.gov.pk/. 

Here are the top 3 individuals I suggest contacting:

Officials:
1. Mr. Omar Ayub Khan, Federal Minister
PHONE: 9212442
FAX: 9224825
2. Mr. Zahoor Hussain Qureshi, Parliamentary Secretary
PHONE: 9222376
FAX: not found
3. Mr. Irfan Ali, Federal Secretary
PHONE: 9211852
FAX: 9206272
4. A full list of ministry officials can be found here: http://www.mowp.gov.pk/frmDetails.aspx 

I am not sure whether or not the phone and fax numbers listed below each name here are extensions. In case they are, then here are the phone and fax numbers of the Ministry of Energy (Power Division) itself:
PHONE: 9209624
FAX: 9203187

More info on telephone numbers in Pakistan: https://en.wikipedia.org/wiki/Telephone_numbers_in_Pakistan

**Comment by martincollignon** [comment]
Zain, this is great. Since you know the country and the language - could
you help us out and reach out to them?

**Comment by UPstartDeveloper** [comment]
Of course!

**Comment by UPstartDeveloper** [comment]
It looks like they are not answering at this time. Possibly because it is 11:35 pm in Islamabad, Pakistan right now. Will try to call them again later!

**Comment by systemcatch** [comment]
Direct link to CEIC data - https://www.ceicdata.com/en/indicator/pakistan/electricity-production

Renewable energy info - https://www.iea.org/policiesandmeasures/renewableenergy/?country=Pakistan

Further contacts
Water and Power Development Authority - http://www.wapda.gov.pk/
Karachi Electric - https://www.ke.com.pk/

**Comment by alixunderplatz** [comment]
National Transmission & Despatch Company:
https://www.ntdc.com.pk/

**Comment by UPstartDeveloper** [comment]
I just sent out a message to Adil Najam (https://www.linkedin.com/in/adilnajam/) asking if can help. He's the Inaugural Dean of the Pardee School of Global Studies, which is a part Boston University, located in Boston Massachusetts. He is also very interested in helping countries in the developing world evolve, and I know that he's from Pakistan as well.

**Comment by UPstartDeveloper** [comment]
Hey team! 
I looked at the IEA site (huge thanks to Chris @systemcatch) - and it looks spectacular!

I found a specific URL on that site that has the information for Pakistan's _historical electricity generation by source_  - so anyone's who's interested should definitely take a look at this link instead, because unfortunately the link above leads to a 404 page: https://www.iea.org/countries/pakistan 

What do you think the next steps should be @martincollignon ? I can resume looking for real time data. Meanwhile is this historical data enough to build the parser?

**Comment by q--** [comment]
Installed capacity: https://www.ntdc.com.pk/energy

**Comment by UPstartDeveloper** [comment]
@q-- thanks for adding your thoughts and links! 

I will email info@cppa.gov.pk to ask about how often the "Market at a Glance" table is updated, and if that has anything to do with why the discrepancy exists.

**Comment by Huzi1** [comment]
@UPstartDeveloper On search to find some data, I think I got something  here 
https://opendata.com.pk/dataset/precon-pakistan-residential-electricity-consumption-dataset

**Comment by madsnedergaard** [comment]
Thanks for all the valuable information shared here! 🙌

We're closing this issue as it is not currently possible to build a real-time parser given the data provided here.
If you find new information that might help us get it done, please comment and reopen the issue [when a parser is buildable](https://github.com/electricityMap/electricitymap-contrib/wiki/Technical-requirements-for-parser-data) :)
