### ISSUE TITLE
Estonia - Carbon intensity (Oil Shale)

### ISSUE THREAD

**Issue by katlavaht** [electricitymap/electricitymap-contrib#2118]
Coal stands actually for [Oil Shale](https://en.wikipedia.org/wiki/Oil_shale) used in **Estonia** for electricity production. Oil shale is a sedimental rock, with high mineral content/low organic content.
Electricitymap currently is using old and very much outdated figure 1515gCO2/kWh_el (Source: EASAC 2007)
The actual figure is around 1000 kg_CO2/MWh_el IMHO.
Propose to use a reference:
**European Residual Mixes** - [Results of the calculation of Residual Mixes for the calendar year 2017](https://www.aib-net.org/sites/default/files/assets/facts/residual-mix/2017/AIB_2017_Residual_Mix_Results_v13.pdf)
Estonian Oil Shale emission factor **1042 kg_CO2/MWh_el**.
This is still much higher than system-wide used emission default factor 820 kg_CO2/MWh_el for coal, but oil shale emissions are higher due to its chemical composition and combustion properties.

**Comment by brunolajoie** [comment]
ref #738 where we compute country-specific emission factors per fuel, in life cycle analysis approach. The EU-28 average for coal-power is computed at 1160gCO2eq/kWh while EE is at 1300gCO2eq/kWh.

**Comment by katlavaht** [comment]
Understood the following:
system-wide default coal emission figure will grow from 820 to 1160 kg_CO2/MWh_el
EE emission factor will be reduced from 1515 to 1300 kg_CO2/MWh_el
Climate impact:
- EE is getting greener
- EU is getting dirtier
Thanks for the Table 1 in https://github.com/tmrowco/electricitymap-contrib/issues/738#issue-255410708.
Not sure how did you get the figure 1300, but the difference between default coal and oil shale emission factors looks fair enough.

**Comment by corradio** [comment]
I'd rather use #738 to fix this particular issue.

**Comment by Kongkille** [comment]
I'm closing this issue in favor of #738
