### ISSUE TITLE
Start timestamp for graphs inferred from the oldest datapoint

### ISSUE THREAD

**Issue by fbarl** [electricitymap/electricitymap-contrib#2250]
This is a problem because we say the graphs show 24 hours of data which is not always true.

1. In most cases, the graphs are really showing a little more than 24h of data which is clear from taking a closer look at the time scales

![image](https://user-images.githubusercontent.com/1216874/75278294-e8171c00-5809-11ea-90bc-85661faf1a45.png)

2. What might be a more serious problem is that from the code it seems that we're not really accounting for the missing data at the _beginning_ of the graphs, as nothing similar to #472 has been implemented for the other end of the graph. I couldn't find a zone to demonstrate this case.

**Comment by corradio** [comment]
Makes total sense!

**Comment by Kongkille** [comment]
This should actually have been fixed now after we changed the data pïpeline :)

![image](https://user-images.githubusercontent.com/45588799/165730685-b357263f-3776-448d-95bf-2fe203cb0baf.png)
