### ISSUE TITLE
Re-introduce animated transitions to left panel elements

### ISSUE THREAD

**Issue by fbarl** [electricitymap/electricitymap-contrib#2336]
Some D3 default transition were removed during migration to React components - it should be easy to re-introduce them either with CSS or React Motion (see https://github.com/tmrowco/electricitymap-contrib/issues/2286).

Only two elements come to my mind that we might want to animate again:

* [ ] `CountryTable` component horizontal bars
* [ ] `AreaGraph` component layers

@corradio can you think of anything else to add?

**Comment by corradio** [comment]
Nope - I agree with you!

**Comment by corradio** [comment]
@fbarl I don't remember - is this still applicable?

**Comment by fbarl** [comment]
> is this still applicable?

Yup, I never got around it, but I'd be happy to take it one if these days when I get an hour or two on the side (although #2481 is still on top of my list there).
