### ISSUE TITLE
Update JP Historic Parser to use occtonet links

### ISSUE THREAD

**Issue by robertahunt** [electricitymap/electricitymap-contrib#2422]
I just realized that occtonet links to csv files for production data which has more recent data than ISEP provides (ISEP only has data until december 2019 at the moment, whereas the individual data providers have data as recent as March 2020), but would require writing quite a few new parsers, which may be less stable than continuing to use ISEP.

link: http://occtonet.occto.or.jp/public/dfw/RP11/OCCTO/SD/LOGIN_login#

**Comment by Kongkille** [comment]
Closing this for now, feel free to reopen if someone wants to take a look :)
