### ISSUE TITLE
Country view shows local time instead of country timezone adjusted one

### ISSUE THREAD

**Issue by smyru** [electricitymap/electricitymap-contrib#2578]
When viewing selected country (ie. https://www.electricitymap.org/zone/AUS-SA) the time and date field below zone / country name shows local (as in viewer one) time instead of timezone adjusted one. See attached illustration. This is somewhat an UX issue, as one may expect output frorm ie. solar that is quite dependent on a time of the day.

![foo](https://user-images.githubusercontent.com/554271/86614000-a3b73c00-bfb2-11ea-9eed-5cd25d3acb7f.png)

This might be somewhat non trivial to apply proper timezone delta, since I can image there might be regions spanning across them.

**Comment by jarek** [comment]
See https://github.com/tmrowco/electricitymap-contrib/issues/802 previously

**Comment by smyru** [comment]
Ah, OK. I have looked for duplicates in the ticket database, yet only among the open tickets.

**Comment by fbarl** [comment]
Thanks for opening the issue @smyru!

> This is somewhat an UX issue, as one may expect output from ie. solar that is quite dependent on a time of the day.

I agree! While #802 proposes a more elaborate solution, I think we could address the UX concern by simply making it more clear in the UI that the user is always looking at the timestamps in _their own time zone_. Perhaps a small question mark with an explanation tooltip or otherwise an explicit time zone info next to the timestamp would already be an improvement. What do you think @smyru?

**Comment by smyru** [comment]
TBH, as long as the date and time given is local for the viewer, there is not much point in placing it in the country/bidding zone box. It brings no added value this way, and in fact can be misleading. 

I am a big fan of energy evolution of South Australia state, and I have kept following its progress over few years now, nevertheless it tricked me, too, despite the fact I am well aware of the time shift between CEST and ACST, and only in afterthought it struck me that had not been right. 

Maybe we shall not look for a solution of a time / bidding zone issue but rather for country/bidding zone capital/administrative centre. First of all this would be a map point, which simplifies acquiring proper time as there is no more ambiguity. Yet the administration centres are in the prevalent cases either population hubs or are close one, where much or most of the population live in the neighboring areas. That would be also natural to viewers, since we are used to read of London time, Beijing time etc.

**Comment by corradio** [comment]
Maybe a quick fix is the add the suffix " (browser time)" to the datetime so it's clear to everyone?
Then as a second step we can think about showing local time?

**Comment by Kongkille** [comment]
As discussed in 802, there are some difficulties in adding specific times on the countryPanel. However, we did try to tackle the core problem with the time slider feature showing an approximation on whether it is day or night 

![image](https://user-images.githubusercontent.com/45588799/165736606-b94af187-ffa3-4e94-8404-d818a9eeeaa9.png)

Feel free to reopen, if this does not address the issue :)
