### ISSUE TITLE
Bolivia: all intermittent renewables reported as wind, but it appears to be mostly solar

### ISSUE THREAD

**Issue by q--** [electricityMap/electricitymap-contrib#2666]
In the Bolivia parser, [all intermittent renewables are reported as wind](https://github.com/tmrowco/electricitymap-contrib/blob/fe275a0e3ae0d15021ea3617df024e992b05354e/parsers/BO.py#L17). However, a look at the [map](https://www.electricitymap.org/zone/BO?wind=true) shows that the "wind" generation displays the curve typical of solar generation (and does so when the sun is up).

It appears the reason intermittent renewables aren't being logged as "unknown" is because that category is already used for thermal generation, which isn't broken down by fuel type in the data source.

Maybe there should be a new category "unknown renewable"?

**Comment by blaltarriba** [comment]
I'm a beginner in the project and I'm looking for an issue to start contributing(a good-first-issue one), so what should be done here? You suggest to set all `itermittent` as a new category `unkown renewable`?

**Comment by q--** [comment]
I'm suggesting creating a new category, 'unknown renewable', similar to how battery storage was added in  #895


However, before beginning work on that someone from Tomorrow should probably weigh in whether they approve of this or if they prefer something different (say, putting everything including wind under solar)

As an aside, there is a ["good first issue"](https://github.com/tmrowco/electricitymap-contrib/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+) label here on GitHub, though it appears to be rather sparsely populated.  
There are also the ["help wanted"](https://github.com/tmrowco/electricitymap-contrib/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) and ["parser buildable"](https://github.com/tmrowco/electricitymap-contrib/issues?q=is%3Aissue+is%3Aopen+label%3A%22parser+buildable%21%22) tags. (I've found building a parser pretty doable, as there's usually an existing parser that does roughly what you need and which you can adapt.)

**Comment by blaltarriba** [comment]
Thank for the advise, I'll take a look on that tags too as `good first issue` tag needs more issues

**Comment by corradio** [comment]
Hi @q-- ,

This is clearly a problem. Adding a new category is something we'd rather avoid.
As a first step, I suggest having wind+solar reported as `unknown` generation, as it clearly is wrong to assume it is one or the other.
As a second step, I suggest overriding the emission factor for `unknown` assuming a static `unknown` mix (e.g. 30% wind, 30% solar and 40% thermal).

**Comment by q--** [comment]
@corradio The problem is that, unlike in other parsers, BO already uses `unknown` for thermal generation so it can't be used for renewables

**Comment by corradio** [comment]
> @corradio The problem is that, unlike in other parsers, BO already uses `unknown` for thermal generation so it can't be used for renewables

Ok. I still think it makes sense to lump together thermal and renewables in `unknown` if we can't separate them individually. That means `unknown` becomes a category that doesn't contain exclusively thermal, and therefore the emission factor of `unknown` must be overwritten.
We shouldn't assume `unknown` is always thermal.

This solution is better than showing solar as wind :)

**Comment by alixunderplatz** [comment]
Hi @q-- 
I think the renewable section was assigned to "wind" back then, because wind energy had a significantly larger share than solar back then (probably based on data <=2017), see IEA graph:
![grafik](https://user-images.githubusercontent.com/25743609/103132566-67cd7b80-46a5-11eb-89db-8b7ccfd103c1.png)

**Comment by q--** [comment]
I suspected something like that.

Well, if introducing a new category isn't an option I suppose I could swap things around and include wind in the solar category.  Slightly less wrong, at least.  
Putting everything under unknown isn't worth it IMO, given that that means losing the distinction between thermal and intermittent renewable generation.

**Comment by corradio** [comment]
Hi @q-- ,

I'm afraid that it won't make sense either to put wind in the solar category. Let me explain the rationale:
The way we build the dataset is by being extremely conservative. We rely heavily on the categorisation of fuels to train different types of machine learning models. For example, when performing electricity forecasts, the solar fuel is forecasted using the solar weather data as explanatory variable. Putting wind in the solar category will therefore affect our forecasting capability, and will end up in incorrect insights in some other models. This means that mixing fuel types isn't a good idea, and hence why we introduced the unknown category for "the rest".
Now I totally understand your rationale to put wind in the solar category, as it yields the least wrong CO2 estimate.
How do you feel about lumping "the rest" into "unknown", which I do realise will mix both renewable and non-renewable sources, and therefore require us to change the default emission factor for "unknown" in Bolivia based on the estimated breakdown of "unknown" fuels?
I also favour this solution as it clearly highlights the shortcomings of the data provider, and would push them to have a better breakdown of their mix as people ask for the breakdown.

Feel free to ping me on Slack in case you want to have a further discussion about this. I also realise it should probably be better explained somewhere.

**Comment by corradio** [comment]
Hi all!
I'm making a pass at all issues to see if we can move forward with a few of them. @q-- did you have time to read my comment?
Olivier

**Comment by KabelWlan** [comment]
This issue is solved since #3553 implemented separate solar and wind data.

**Comment by madsnedergaard** [comment]
Thanks for the much needed cleanup, @KabelWlan 😄
