### ISSUE TITLE
Cross border flow from North Norway (NO4) to Sweden is wrong

### ISSUE THREAD

**Issue by Gazer75** [electricitymap/electricitymap-contrib#2699]
Because Sweden is one region in map the flow is wrong and only showing flow for NO4-SE2. The parser need to combine both SE1 and SE2 flows to NO4.

Best thing is to actually split up Sweden in its proper regions.

**Comment by Kongkille** [comment]
Hey @Gazer75, I'm not quite sure I understand. I agree there are a bunch of issues with not having Sweden split #1397. Is there something we can do except split Sweden?

**Comment by Gazer75** [comment]
The problem is the current code is only displaying transfers between North Norway (NO4) and SE2.
This is about 1/3 of the total normally exchanged to/from NO4 as most is going to/from SE1.
Reason for this is the NO4-SE2 exchange is on a 220kV line while the NO4-SE1 is over a 420kV line.
https://www.statnett.no/en/for-stakeholders-in-the-power-industry/data-from-the-power-system/
https://openinframap.org/#6.23/66.768/15.878

Hoping there is some way to code it so that the combined total of the two are shown on the map until Sweden is split into its proper regions.

**Comment by corradio** [comment]
Hi @Gazer75 ,
Indeed I confirm the issue, as can be seen from the code at
https://github.com/tmrowco/electricitymap-contrib/blob/master/parsers/ENTSOE.py#L173-L174

The ENTSOE.py parser currently doesn't support summing multiple interconnectors, and I guess this could be made as an improvement to avoid having to split SE.
