### ISSUE TITLE
Improve geometries of Cyprus

### ISSUE THREAD

**Issue by dsaw** [electricitymap/electricitymap-contrib#2724]
Most parts of the world map are correctly charted as such, but a few of the regions if you zoom in a bit have got inaccurate borders. 
For example, Northern Cyprus and Cyprus seem to have body of water between which is incorrect - they are part of the same island.
I figure the map might not be intended to scale since its used to track energy consumption and all. Though it would be great to improve these parts.

![image](https://user-images.githubusercontent.com/5353891/95663362-448e3800-0b5c-11eb-946b-080f91116cc3.png)

**Comment by veqtrus** [comment]
That one is because of https://en.wikipedia.org/wiki/United_Nations_Buffer_Zone_in_Cyprus I think.

**Comment by Kongkille** [comment]
Generally, there's a lot to improve on the geojson of the map. Especially in the US, if someone is interested in trying to improve this, let me know. It will require some manual work, but hopefully through this process we can find a better solution to improving the borders

**Comment by dougfabris** [comment]
@Kongkille Could you give more details about the improvements needed? I'm interested to help with that! 
Btw I'm going to raise a PR to fix the Cyprus region. @veqtrus You mean, we should skip the dashed part of the island? 

![image](https://user-images.githubusercontent.com/27704687/162648910-56dc2dcb-69cf-4664-8a8a-58fad372b6ee.png)

**Comment by veqtrus** [comment]
AFAIK, both the DMZ and the [British bases](https://insidedio.blog.gov.uk/2018/10/10/powering-up-raf-akrotiri/) are powered by Cyprus. The bases are not part of the republic though so not sure if they should be displayed separately.
