### ISSUE TITLE
More data for Georgia (Country): forecast + historical

### ISSUE THREAD

**Issue by q--** [electricitymap/electricitymap-contrib#2838]
http://gse.com.ge/for-customers/data-from-the-power-system/production-and-consumption

The download button lets you download an XLS file with more detail than the graph; it also has a generation breakdown. (Check the two tabs, "Plan" and "Fact", for forecast and actual production.)

![Planned Georgia Generation Breakdown Excel Sample](https://user-images.githubusercontent.com/2470175/101661757-f658c080-3a48-11eb-9890-9ce74ab2c1e9.png)

Solar production appears to be zero in the XLS unfortunately (it's missing completely from the real-time data we're using now), so either they don't have utility-scale solar plants yet or the data is missing.

**Comment by madsnedergaard** [comment]
The historical data part was addressed in #2847 so closing this again :)
