### ISSUE TITLE
Data for Iraq IQ

### ISSUE THREAD

**Issue by euanEmber1** [electricitymap/electricitymap-contrib#2852]
Hi Electricity mappers! Euan from Ember here - we're putting together data for an upcoming report, and I stumbled across this: https://www.gdoco.org/

It's real-time electricity data for Iraq, including a split by region, as well as flows between regions. I couldn't see data for Iraq on your frontend so thought I would share!

If you come across a way to query for data from specific times then please let us know - we're all about historic monthly datasets, so would love to get our hands on some for Iraq.

**Comment by byronwilliams** [comment]
For the live data (the only bit I'm particularly interested in) - the URL is here - https://www.gdoco.org/generation.html

Their page uses this URL to get the data https://www.gdoco.org/vueips.php - where each `d_{id}` corresponds to an item in the crazy HTML table. So to extract the South Gas you'd be looking for `d_1215` (`td[title="1215"]`). It looks pretty easy to get this into a PR. So I can do that this week.

**Comment by byronwilliams** [comment]
Works locally for me too. Could your IP have been blocked on the server?

**Comment by madsnedergaard** [comment]
I guess that could be it. How have we previously dealt with blocked IPs, @corradio?

**Comment by madsnedergaard** [comment]
We are indeed being blocked, this is the result when calling directly from the server (inspired by #2461):
<img width="1049" alt="Screenshot 2021-04-09 at 17 57 30" src="https://user-images.githubusercontent.com/3296643/114207841-19df3980-995d-11eb-9e24-8646090cf134.png">

I'll reach out to them :)

**Comment by corradio** [comment]
> We are indeed being blocked, this is the result when calling directly from the server (inspired by #2461):
> <img alt="Screenshot 2021-04-09 at 17 57 30" width="1049" src="https://user-images.githubusercontent.com/3296643/114207841-19df3980-995d-11eb-9e24-8646090cf134.png">
> 
> I'll reach out to them :)

Great! It often pays off the reach out to them :)

**Comment by madsnedergaard** [comment]
I have sent an email now, will update when I get a response.

**Comment by Kongkille** [comment]
@madsnedergaard did you receive an update?

**Comment by madsnedergaard** [comment]
Nope, but it also seems like the dashboard is no longer available, so let's close this for now :)
