### ISSUE TITLE
Partly Permanent Shutdown of german coal fired power plants

### ISSUE THREAD

**Issue by moinmoin2** [electricitymap/electricitymap-contrib#2889]
In Germany the installed capacity of coal fired power plants has changed, beacause of the permanent shutdown of some german coal fired power plants. Now we have exactly 5085MW of installed capacity less in Germany. In the following i will post the source of my information for the brown coal power plant Niederaußem D (297MW), Pfeiffer und Langen GmbH & Co KG (22,86 MW). 
The hard coal power plants Westfalen (764 MW), Ibbenbüren (794 MW), Walsum 9 (370 MW), Heyden (875 MW), Zuckerfabrik Warburg (4,6 MW),  Moorburg A and B (2x 800 MW), Bremen Hafen Block 6 (303 MW), Infraserv GmbH & Co. Höchst KG(51MW), Zuckerfabrik Brottewitz in Brandenburg (3,57 MW). Please correct the installed capacity on electricitymap in germany.

Source: https://www.iwr.de/news/welche-kohlekraftwerke-2021-abgeschaltet-werden-sollen-news37127
Source 2:https://de.wikipedia.org/wiki/Kraftwerk_Niederau%C3%9Fem

**Comment by q--** [comment]
The Wikipedia article linked lists one plant decommissioned in December 2020, but the other article, at least according to Google Translate, lists power plants to be closed *in* 2021, not *by* 2021. Translation error?

I've checked the ENTSO-E data for Germany and it lists a bit of a drop in lignite capacity, but hard coal seems to actually have gone up a bit.  https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&dateTime.dateTime=01.01.2019+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2022+00:00|UTC|YEAR&area.values=CTY|10Y1001A1001A83F!CTY|10Y1001A1001A83F&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19

I've also found the [Bundesnetzagentur power plant list](https://www.bundesnetzagentur.de/EN/Areas/Energy/Companies/SecurityOfSupply/GeneratingCapacity/PowerPlantList/PubliPowerPlantList_node.html), installed coal capacity is [a bit different from the ENTSO-E data](https://www.bundesnetzagentur.de/SharedDocs/Bilder/DE/Sachgebiete/Energie/Unternehmen_Institutionen/Versorgungssicherheit/KWnetto_04_2020.jpg?__blob=poster&v=2), but that could be explained by the fact that this data is from April 2020, not the start of the year like the ENTSO-E data.

Anyway, I don't see 5085MW drop in coal capacity in this data. Maybe they've been mothballed but not actually decommissioned?

**Comment by moinmoin2** [comment]
> 
> 
> The Wikipedia article linked lists one plant decommissioned in December 2020, but the other article, at least according to Google Translate, lists power plants to be closed _in_ 2021, not _by_ 2021. Translation error?
> 
> I've checked the [ENTSO-E data for Germany](https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&dateTime.dateTime=01.01.2019+00:00%7CUTC%7CYEAR&dateTime.endDateTime=01.01.2022+00:00%7CUTC%7CYEAR&area.values=CTY%7C10Y1001A1001A83F!CTY%7C10Y1001A1001A83F&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19) and it lists a bit of a drop in lignite capacity, but hard coal seems to actually have gone up a bit.
> 
> I've also found the [Bundesnetzagentur power plant list](https://www.bundesnetzagentur.de/EN/Areas/Energy/Companies/SecurityOfSupply/GeneratingCapacity/PowerPlantList/PubliPowerPlantList_node.html), installed coal capacity is [a bit different from the ENTSO-E data](https://www.bundesnetzagentur.de/SharedDocs/Bilder/DE/Sachgebiete/Energie/Unternehmen_Institutionen/Versorgungssicherheit/KWnetto_04_2020.jpg?__blob=poster&v=2), but that could be explained by the fact that this data is from April 2020, not the start of the year like the ENTSO-E data.
> 
> Anyway, I don't see 5085MW drop in coal capacity in this data. Maybe these power plants have been mothballed but not actually decommissioned?

The block D of the brown coal power plant Niederaußem has been permanently shuted down since the 31.12.2020. The rest of the coal power plant Niederaußem will shuted down in the next years. Only this Block is powered down for ever. All Coal Power plants in germany will be permanently shuted down until 2038. This does not a happen simultaneously. So nearly every year one or more power plants will be closed and the power plant niederaußem D is the first one

**Comment by KabelWlan** [comment]
This could be closed since it is outdated and already changed. The last capacity update was in December, see #3622.
