### ISSUE TITLE
[Quality Assurance] Notify when production > [total] capacity

### ISSUE THREAD

**Issue by Manu1400** [electricitymap/electricitymap-contrib#2939]
Notify in [runtime logs](https://kibana.electricitymap.org/app/kibana#/discover) when : 
* total production > total capacity
* production > capacity (i.e: wind production > wind capacity)

**Comment by madsnedergaard** [comment]
We had this, but it was removed in #3955. We're currently reworking our internal data quality layer, so we expect to address these issues earlier in the pipeline in the future :)
