### ISSUE TITLE
Frontend doesn't always center on user location

### ISSUE THREAD

**Issue by corradio** [electricitymap/electricitymap-contrib#3024]
I identified a race condition which results in the map sometimes centring on the user's location and sometimes not.
The race condition is located here:
https://github.com/tmrowco/electricitymap-contrib/blob/master/web/src/layout/map.js#L56-L59
When the map is loaded, if `callerLocation` is provided, then the map will center properly. However, if the `callerLocation` is not available yet (as the `callerLocation` is obtained from the /state call to the electricityMap backend), then the map will not center.

Tasks:
- move the "callerLocation" code out of `handleMapLoaded` and use it in render

**Comment by evcheng1** [comment]
I am interested in taking this issue as well as #3002. Thanks!

**Comment by dougfabris** [comment]
@corradio I could reproduce the issue on production but without success in development. There's no data on `callerLocation`, am I missing something here?

**Comment by corradio** [comment]
> @corradio I could reproduce the issue on production but without success in development. There's no data on `callerLocation`, am I missing something here?

`callerLocation` is populated on the backend but I don't think it is present on the mockserver.
However, I've been able to propose a fix at https://github.com/electricitymap/electricitymap-contrib/pull/3955
