### ISSUE TITLE
Explore real-time data access from regional and state despatch centres in India

### ISSUE THREAD

**Issue by gwpicard** [electricitymap/electricitymap-contrib#3102]
Add to what has been ongoing to adding India data in #304 

------------------------------
From what I understand, the Indian grid works in the following way:

1. There is a national grid operator, POSOCO, which oversees the operation of the national grid as well as the regional grids. The national grid is split into 5 Regional Load Despatch Centres (RLDC) (Northern, Eastern, Western, North Eastern and Southern Grids).
2. Each of the 5 RLDCs manage operations within the regional grid as well as intra/inter-regional and trans-national interconnector exchanges:
    - Northern Region - https://nrldc.in/
    - Eastern Region - https://erldc.in/
    - Western Region - https://www.wrldc.in/
    - North Eastern Region - https://www.nerldc.in/
    - Southern Region - https://srldc.in/
3. Each grid region is made up of states each with their own State Load Despatch Centres (SLDC). I won't list them all the SLDCs here but they are responsible for coordinating state-level grid operations and with the POSOCO national + regional grids. Some examples:
    - [Maharashtra State Load Despatch Centre](https://mahasldc.in/home.php/)
    - [Punjab State Load Dispatch Centre](https://www.punjabsldc.org/about.aspx)
4. [It should be noted that there are also transmission and distribution companies at the different geographical levels (typically separate from despatch centres) which are responsible to managing and maintaining the operations of the actual infrastructure such as transmission lines and substations]
5. The SLDCs are responsible for managing the grid in the state and also account for IPP/CPP (private) generators within the distribution network that aren't accounted for with a much granularity by POSOCO. SLDCs therefore have full visibility into how much power is coming from POSOCO generation (central sector), state-level generation (state sector) and from IPP/CPP generation (private sector).

If we are able to combine data from national-level NDLC/RDLC POSOCO operations with data from state-level SLDC operations, we would essentially have combined real-time data for production and interconnector exchanges for all of India.

I wonder if we could investigate every RLDC and every sub-regional SLDC and see if they have real-time data since they monitor the grid minute-to-minute and also sometimes publish daily reports with hourly breakdown.

For example:
- real-time data from the [Western RLDC](https://www.wrldc.in/content/164_1_StateScheduleVsActual.aspx)
- real-time data from the [Maharashtra SLDC](https://mahasldc.in/home.php/report2/)

**Comment by alixunderplatz** [comment]
Hi @gwpicard
thank you for your comment! 
Back in the days in 2018 I spent quite a while looking for reliable data for India, going through all the LDCs and state/regional grid companies websites.

Based on the probably most complex and very oddly meshed national grid of the world, it still really seems impossible to ever make a perfect split of the regions and cover each state or grid region, unless data will be disclosed reliably on a centralized website.

Visualize the Indian HV grids here: https://openinframap.org/#4.85/20.45/80.75
![grafik](https://user-images.githubusercontent.com/25743609/116746254-7e416600-a9fc-11eb-8877-50658d3e1771.png)


The only option I still see and want to promote is to finally display **India as a whole**. 
The parser was created by @systemcatch back in #1664 based on the hi-resolution http://meritindia.in/ data that I found in 2018 described in #304. 
______

@corradio I try to bother you at least once a year (😄), but maybe it is about time to switch to "India as a whole", because most of India's states haven't been showing reliable or realistic data for some time now. 
Plus, you'd cover an area with 1.300.000.000+ inhabitants // 160+ GW demand/production in a single action.

Kind regards, Alex :)

**Comment by gwpicard** [comment]
@alixunderplatz Thanks for the response!

I did take a look at the conversation from those threads and I think at the moment my understanding is that we would prefer moving toward a region/sub-regional granularity for India (would you say this is the case @corradio?).

The reason I created this issue is that I believe that we are quite close to having real-time data for most of India (especially as advances have been made over the last few years), but it's a question of consolidating some of what has been found in #304 along with any other possible sources of real-time data for each region and sub-region. The other issue too is that some of this data may not be exposed, or is behind a login wall. For example:

**Potential realtime data for NERLDC grid region**
![Screenshot 2021-05-04 at 11 15 37](https://user-images.githubusercontent.com/7591224/116983172-0f992c80-acca-11eb-9d94-87d98813a767.png)

**Potential realtime data for NRLDC grid region**
![Screenshot 2021-05-04 at 11 16 36](https://user-images.githubusercontent.com/7591224/116983295-32c3dc00-acca-11eb-979d-184988448ac3.png)

**Potential realtime data for SRLDC grid region**
![Screenshot 2021-05-04 at 11 17 49](https://user-images.githubusercontent.com/7591224/116983423-5e46c680-acca-11eb-9eb0-250fb1be765b.png)

Just with these 3 Grid regions ([WRLDC already has realtime data available](https://wrldc.in/content/2_1_DataDashboard.aspx#)) and a further investigation on included sub-regional states, I am quite confident we would be able to map out a large amount of production at a regional and sub-regional level in realtime without needing an India-wide map.

It would take some time but having spent some time focusing on the Western region, there is alignment at the regional level on production numbers from the states because they regional operators are the overall grid operators. The question then is to create the system at the regional level, and then break it down at the state-level accounting for production in each state (and eventually cross-regional and cross-state flows).

**Comment by corradio** [comment]
I don't have a strong opinion on the spatial resolution to use.
Down the line it'd be great if we had the ability to do both! See #2954

**Comment by Kongkille** [comment]
Hey guys, I'm closing this issue for now, as it is referenced in our other issue for India which can be accessed from our main issue if there's any news :)

**Comment by ashokavi12** [comment]
GRID INDIA ( Formerly known as POSOC)

**Comment by Insuryance** [comment]
This is interesting. Has there been any update on this? Accessing accurate real time data on a state level bifurcation in India?

**Comment by VIKTORVAV99** [comment]
> This is interesting. Has there been any update on this? Accessing accurate real time data on a state level bifurcation in India?

There has not, this issue has been closed a while now and I don't think anyone is working on this anymore.

**Comment by Insuryance** [comment]
Got it. Nevertheless, I'm seeing few open source APIs being formed via few DISCOMS. If I'll get the access, I'll update it here as a continuation. Thanks for the reply! @VIKTORVAV99

**Comment by VIKTORVAV99** [comment]
> Got it. Nevertheless, I'm seeing few open source APIs being formed via few DISCOMS. If I'll get the access, I'll update it here as a continuation. Thanks for the reply! [@VIKTORVAV99](https://github.com/VIKTORVAV99)

Feel free to open a new issue, there is not many people monitoring these old ones.
