### ISSUE TITLE
Support for `Ocean` Emission Factor

### ISSUE THREAD

**Issue by pierresegonne** [electricitymap/electricitymap-contrib#3105]
Some countries have experimented with tidal power and report it in their production data (e.g Korea as reported in these [capacities](http://epsis.kpx.or.kr/epsisnew/selectEkpoBftChart.do?menuId=020100) ) and the [IPCC 2014 report](https://archive.ipcc.ch/pdf/assessment-report/ar5/wg3/ipcc_wg3_ar5_annex-iii.pdf#page=7) that we use currently for the base of some of our emission factors have an estimate for `ocean` .

Based on that, we could add it to our supported production modes. Nevertheless considering the limited scale of tidal power use, I'd like others' opinion on whether it's even useful to include this production factor or not.

**Comment by q--** [comment]
In the FO parser I added it as 'other' with the IPCC emission factor as an override.


Obviously that's only viable if no other electricity source is already using the `other` category

**Comment by Kongkille** [comment]
When we address #738 we'll also look into how to handle new and other production modes
