### ISSUE TITLE
Open Live Data for UK's "Western Power Distribution"

### ISSUE THREAD

**Issue by alixunderplatz** [electricitymap/electricitymap-contrib#3127]
Hi everyone,
found this via twitter of @russss (who is the maintainer of the awesome Open Infrastructure Map, 
see https://openinframap.org):

https://twitter.com/russss/status/1387169573611442183
![grafik](https://user-images.githubusercontent.com/25743609/116742800-30c2fa00-a9f8-11eb-8fea-cf62d2ae8a5c.png)

The data can be found on this website and seems to cover a few sources plus demand, generation and imports.
https://connecteddata.westernpower.co.uk/dataset/live-data

Title | Type | Label | Description | Example
-- | -- | -- | -- | --
Timestamp | timestamp |   |   |  
Demand | numeric |   |   |  
Generation | numeric |   |   |  
Import | numeric |   |   |  
Solar | numeric |   |   |  
Wind | numeric |   |   |  
STOR | numeric |   |   |  
Other | numeric |   |   |  

There is an API, even with some python example code, and/or csv-files available.

I have no capacity to look into this deeper, so I just leave it here four you folks :-)
Even if it's not enough to break it down to all sources of the mix, it could be useful in the future.

Kind regards! Alex

**Comment by martincollignon** [comment]
@corradio are there updates on the regional split for UK?

**Comment by corradio** [comment]
> @corradio are there updates on the regional split for UK?

See https://github.com/tmrowco/electricitymap-contrib/issues/1894

**Comment by Manu1400** [comment]
great graph: https://www.westernpower.co.uk/our-network/live-data-feed-application-data-view

**Comment by Kongkille** [comment]
Hi, I'm uncertain what the next action items would be. Perhaps we can look into it again if we decide to move forward with the regional split of UK? 

I'm closing for now, feel free to reopen :)
