### ISSUE TITLE
Jersey <-> France interconnect ?

### ISSUE THREAD

**Issue by ajoga** [electricitymap/electricitymap-contrib#3134]
Jersey is an island close to metropolitan France that "receives 95% of its electricity from France through three undersea cables."

Can we find data to scrape about this interconnect and Jersey's consumption ?

I couldn't find data on:
- the open data platform of the Government of Jersey https://opendata.gov.je/
- Jersey Electricity (the local electricity authority it seems) https://www.jec.co.uk/ 

[1] https://www.theguardian.com/uk-news/2021/may/05/jersey-french-threat-cut-electricity-post-brexit-licences-boats

**Comment by ssmssam** [comment]
This document is back from 2016 but sounds like Jersey flows are already taken into account, so could be the potential to double count here. 

"French physical energy and power flows towards Great Britain takes into account exports made towards Jersey island. "

https://eepublicdownloads.entsoe.eu/clean-documents/Publications/Statistics/Specific_national_considerations.pdf

**Comment by jarek** [comment]
... however, our FR->GB exchange information now comes from Elexon (a British organization) rather than ENTSO-E (where the quote is from)

https://github.com/tmrowco/electricitymap-contrib/blob/15dac811d41dbda25c13112565f91f7008a37252/config/exchanges.json#L1180-L1194

so it might be worth checking whether Jersey is included in Elexon data

**Comment by ssmssam** [comment]
oh sorry yeah! I will check with Elexon to see if they also include the Jersey flows as I thought their numbers matched up with ENTSO-E. And see if they have any Jersey data too.

**Comment by alixunderplatz** [comment]
Based on the fact 95% of electricity comes from FR and a relatively small share is generated on Jersey and Guensey (which are interconnected with each other as well), we could neglect the influence of this connection on the total mix. The islands are not a part of the map at the moment, so I'll close this issue.
See https://openinframap.org/#7.99/49.478/-2.178 for the position of the subsea cables :)
