### ISSUE TITLE
Possibly useful UAE nuclear data

### ISSUE THREAD

**Issue by q--** [electricitymap/electricitymap-contrib#3190]
# Background:

Some time ago I added a parser for [Gulf Countries consumption data](https://github.com/tmrowco/electricitymap-contrib/issues?q=GCCIA)
They're not on the map because imports/exports are missing. (Off-topic, but IMO someone needs to look if they still can show up because 1. imports/exports might be insignificant, which was deemed good enough for Kuwait, or 2. their [app](https://www.gccia.com.sa/gcciamobile.html) might actually have the data we need, though extracting that will likely involve capturing traffic using something like Fiddler2 or Wireshark in order to figure out their API.)

# What's new
Back on-topic, I noticed the website of the [Emirates Nuclear Energy Corporation](https://www.enec.gov.ae/) now has a total GWh generated counter on the home page. The incrementing number is just client-side JavaScript, but the starting number comes from the server and is updated on each refresh (look for `count-air` in the page source, it's the `<div id="count-air"  data-num="` one).

If this is based on actual production (and not just calculated from some hard-coded starting point server-side) it should be possible to derive which part of UAE generation is nuclear.

## So how do we figure out if this is not hardcoded?
Two options:

1. Look for slight fluctuations in generation; if one day has (fake number) 28.1234 GWh of generation and the next one (also fake number) 28.0012 GWh, it's likely based on real generation.
2. Wait for an outage. The plant first (specifically, Unit 1) [went critical in July last year](https://www.enec.gov.ae/en/news/announcements/unit-1-first-criticality/), so the first refueling outage probably still needs to happen. (Refueling usually happens every 1-1½ years for pressurized water reactors.) If the number in the source code stays the same during refueling, that's another indication that we're seeing real data here.

**Comment by veqtrus** [comment]
Some newer power plants have 2 year refuelling cycles though I don't know about this one.

A parser would have to store previous data points in order to accurately estimate production. I'm not sure how it could be done with the current architecture.

**Comment by Kongkille** [comment]
As @veqtrus mentions, I don't see a good way to add this into our current architecture. We can always use it for modeling in the future.

For now, I'm closing this issue :)

**Comment by intermittentnrg** [comment]
I have started archiving https://www.enec.gov.ae/ snapshots at 15 minute intervals to https://github.com/intermittentnrg/intermittent-enec-sns-sqs
The github repository is updated once per day.

I also have archives of some [other sources in my GH org](https://github.com/intermittentnrg?tab=repositories&q=sns-sqs
). Hope this will be useful to someone.

**Comment by VIKTORVAV99** [comment]
> I have started archiving https://www.enec.gov.ae/ snapshots at 15 minute intervals to https://github.com/intermittentnrg/intermittent-enec-sns-sqs
> The github repository is updated once per day.
> 
> I also have archives of some [other sources in my GH org](https://github.com/intermittentnrg?tab=repositories&q=sns-sqs
> ). Hope this will be useful to someone.

Didn't know about these archives! Great work!

I'll go thought them and check if it's something we can use with our current methodology!

**Comment by intermittentnrg** [comment]
The other archives you already have importers for: AESO (Alberta, Canada), ONS (Brazil) and Taipower (Taiwan).

- AESO has historical data at lower resolution (the realtime data is every minute, historical maybe 15m&hourly I forget) https://www.aeso.ca/market/market-and-system-reporting/data-requests/historical-generation-data/
- Taipower has historical data but only at daily average https://www.taipower.com.tw/2764/2826/2829/2832/25093/normalPost or with IPP (Indenpendent) data missing https://data.gov.tw/datasets/search?qs=dtid:465&order=downloadcount&type=dataset
- Ons I'm not sure I didn't work enough with it.

I suspect your crawler has good archive already. Nevertheless it's good to have backup source.

I ended up using HTTP > AWS Lambda w/ EventBridge Scheduler  > SNS > SQS > GitHub actions. I also fan out to SQS to my importers in staging&prod.

GitHub actions are not reliable enough to run directly and high overhead in runtime.
Git repos are automatically compressed so don't need to zip or gz.
I also considered AWS S3 they charge minimum 128 KB per object and there's tonnes of tiny files. Batching and recompressing old files is an option, but not a great one.
At first I parsed in the Lambda and stored parsed values only in DynamoDB but it's another intermediate data format and there can be bugs in the parser which means lost or missing data.
Maybe I could consider archiving locally and making available to internet in case the GH repos get ridiuclously big.

So now I only archive raw data, full CSV/JSON/HTML snapshots.

**Comment by VIKTORVAV99** [comment]
We do something similar with schedulers in GCP, running every 20 min and then putting it structured in our DB directly so we can run quality validation on every data point before it goes into our processing pipelines.

However we are aware we are possibly loosing out on some data that could be useful in the future but not saving the raw data of the sources.

If size becomes an issue please let us know, I think we could set up some bucket storage to keep the snapshots in and make them public if needed, possibly cached in CloudFlare if we need to as long as it's not ridiculous volumes.

**Comment by intermittentnrg** [comment]
This is compressed sizes from https://github.com/settings/repositories They've been running for 2 years soon. AESO archives a CSV once per minute. Taipower a JSON every 5 mins. I just noticed the checkout is getting slow in GH actions. Could split repo per year maybe.
<img width="667" height="405" alt="Image" src="https://github.com/user-attachments/assets/a9c3b108-ad48-4c91-b41f-35e61a8b7356" />

Would be easy to host or mirror on HDDs locally from my homelab, it's probably a good idea. I try to stay in AWS free tier for AWS Lambda/SNS/SQS.
Many more sources lack history, parts of Japan off the top of my head. And sources with history sometimes prune the long tail.
Missing data is more of an issue for me as I make timeseries graphs and gaps in data are super visible.
I don't have a budget or contributors for my project so I appreciate the offer! ❤️
And you could easily archive data yourselves. Having redundant archiving would be great. Tho it's a bit retarded that you can't query historically from source.

**Comment by intermittentnrg** [comment]
Also back to ENEC. The data is a counter, always counting up. This is well handled by many timeseries databases, I use [TimescaleDB](https://github.com/timescale/timescaledb/) which has excellent support https://www.tigerdata.com/docs/use-timescale/latest/hyperfunctions/counter-aggregation

This supports for example network interface statistics that have packets/bytes counters that are always increasing.

I added new intermediate table for counter data to record this and will run query with `counter_agg()` to convert this instantaneous snapshots in main table. Thought it could also be queried directly thru DB views which I have pondered for different scenarios for some time.

My code is on github I can link it when pushed, if wanted, just ask.

**Comment by VIKTORVAV99** [comment]
Very nice!

I'll make sure to bring it up to the team and see if we can set up some archiving of our own as well just in case.

We already have quite a bit of history in the DB we can re-construct some data from if needed but getting the raw data would of course be better (and something we have discussed before).

**Comment by intermittentnrg** [comment]
Yeah DB is my primary store I don't store source data otherwise.

But I'm a bit nervous working with these sources without history, a small mistake can cause a gap in an otherwise flawless 2 year run.
Maybe this has changed now that it's been running stable for ~2 years, but I lost weeks/months of early data because I wasn't parsing all data.
Also for it to be useful to 3rd parties the raw originals seems like the best and most stable.Presumably HTML&CSV compresses very well. Tho it doesn't compare to the 96-99% compression ratio of time series data in TimescaleDB.

<img width="952" height="301" alt="Image" src="https://github.com/user-attachments/assets/cac24b6c-4daf-498e-8373-d1d54a06352e" />

https://www.timescale.com/blog/time-series-compression-algorithms-explained/
(they sponsor me with free cloud hosting so I'm quite happy to advertise them lol! but mostly TsDBs are awesome)

**Comment by VIKTORVAV99** [comment]
We have looked into TimescaleDB but the pain in for us would be migrating everything, it's not easy when you have terabytes of data and your system can have 0 downtime 😅

We might revisit it in the future but so far what we have right now works.

Pretty cool they can compress it that much though!

But these gaps are the reason we created our estimation engine, there is simply no way to avoid them sometime when the source goes offline or report bad data.

**Comment by intermittentnrg** [comment]
Yea DB migrations are a pain. I want to migrate my DB to another cloud region but I expect it to take at least a full day so I've been putting it off for years now lol. Tho it's not too bad when you actually get on with it.
I might just take my site offline for a day to migrate if I did it now. Tho there are tools to do incremental data transfers so can be done without downtime.

I only do real datapoints so this is more important for me. Also my GH actions or homelab are not as reliable as GCP/AWS. I could consider simulations but I don't really have the bandwidth for it, tho an AI might do a good job at it. And I don't mind gaps if provider is actually lacking data. Also you had chaos with Co2 calculations on social media when data was incorrect lol.

There's many other cool timeseries DBs also. QuestDB, VictoriaMetrics, InfluxDB, and many more. Pit of success they are all awesome.
I like Timescale for being proper SQL on top of PostgreSQL (influxdb was/is NoSQL with SQL-like interface), retroactive data updates (some are append only), and insane compression (most don't have compression).

**Comment by VIKTORVAV99** [comment]
Oh yes, the twitter storms...

There are for sure risks with estimations if you are not careful enough, like accidentally showing nuclear in Germany a few months after it shut down due to the fact that it had always been there historically. That was a fun one to deal with 😅 

But since we do flowtracing we need to have 100% completeness otherwise it affects the bordering zones even more than if the estimations are slightly off in 99% of the cases, especially since many providers are delayed by 2-48 hours. The map would be pretty boring if all you could see was Australia and California that have 5 minute data and short delays.

But yeah it took a long time to get that to a good state.

**Comment by intermittentnrg** [comment]
lmao yes, I think I'll pass on simulations.

> when you have terabytes of data and your system can have 0 downtime

On the upside with 90%+ compression you will save terabytes in storage! I have 98.6%-96% compression , tho my tables have 3 only columns (time, area_id, value).
CERN switched from Oracle to TimescaleDB and got 90%+ compression: 68TB -> 6.6TB for a 61.4TB saving. https://x.com/michaelfreedman/status/2020532224580338019

And yea switching DB is a pain, especially at this csale. Update all app to write to two DBs, sync all data which takes days, switch apps to query new DB, remove old DB from all apps, then retire old DB. 🍰 (Maybe you should hire me!). But idk how sensitive you are to ongoing storage costs.

**Comment by VIKTORVAV99** [comment]
> (Maybe you should hire me!)

If you are interested feel free to drop some contact details at viktor.andersson@electricitymaps.com and I can set something up and pass it along internally!

But yeah, we are cleaning up a lot of things internally right now and re-thinking some old choices. Maybe a move to a timeseries database will be part of the next steps. Only time will tell but right now there is a high focus on reducing processing delays and ingesting more data to help our forecasts become even better.
