### ISSUE TITLE
[question / proposal] Split Korea 🇰🇷 

### ISSUE THREAD

**Issue by Manu1400** [electricitymap/electricitymap-contrib#3258]
We could split the KR zone into *regionals* zones like in this map: https://cms.khnp.co.kr/publish_en/img/04/img_0401020300_01.png

![map-hydro-in-kr-zone](https://user-images.githubusercontent.com/3307236/127778584-023656f0-6936-4d08-963a-99d7572bcea0.png)

cc. @jarek

**Comment by Manu1400** [comment]
FYI: This map http://epsis.kpx.or.kr/epsisnew/selectEkpoBftChart.do?menuId=020100 displayed old stats by region

**Comment by Kongkille** [comment]
We now have live data which is aggregated per the country as a whole. It's based on our own estimation model and at the time we could not find any alternative data sources.

So unless new data sources appear, there is not a lot for us to do right now :)
