### ISSUE TITLE
data-QA: get live battery storage from Hornsdale Power Reserve (in Australia 🇦🇺 )

### ISSUE THREAD

**Issue by Manu1400** [electricitymap/electricitymap-contrib#3271]
### now
In [zone AUS-SA](https://www.electricitymap.org/zone/AUS-SA) 🇦🇺 we have live data for battery storage

### Proposal
For validate this data, we could compare to live data from "Hornsdale Power Reserve", a 150MW/194MWh grid-connected energy storage system.

### Documentation
* [Wikipédia (en)](https://en.wikipedia.org/wiki/Hornsdale_Power_Reserve)

### Source
* graph : https://hornsdalepowerreserve.com.au/ => https://timeseries.global-roam.com/u/#/embeddables/b312c706-5a62-40ff-92f9-ea7d8be85164
* data export in CSV => 

Time (UTC+10) | Battery Discharging (MW) | Battery Charging (MW)
-- | -- | --
03-Aug-2021 08:45 | 22.4 | 0
03-Aug-2021 08:50 | 0 | -25
03-Aug-2021 08:55 | 0 | -43
03-Aug-2021 09:00 | 0 | -32.4

**Comment by Kongkille** [comment]
Interesting idea! The team is also working on a QA layer. Hopefully we'll be able to open up more data quality and analysis to contrib soon :)

I'll close this for now, as I think there are more immediate needs in terms of QA right now.
