### ISSUE TITLE
get regional prices in NZ 🇳🇿 

### ISSUE THREAD

**Issue by Manu1400** [electricitymap/electricitymap-contrib#3272]
get regional prices in New Zealand 🇳🇿  in realtime :
* https://www.em6live.co.nz/PlanningRegion.aspx?planningregion=uni
* or https://www.em6.co.nz/em6/faces/pages/login.jspx (same content)

### checks
- [X] Data is live (± 5 mn) 🔥 

### warnings ⚠️
* [NZ-NZST zone](https://www.electricitymap.org/zone/NZ-NZST) is with [NZ-NZS zone](https://www.electricitymap.org/zone/NZ-NZS), visible on https://www.em6live.co.nz/PlanningRegion.aspx?planningregion=lsi
* is it *futur* prices on map ?

**Comment by madsnedergaard** [comment]
Closing this as the zone has been replaced with a new zone for the entire NZ :)
