### ISSUE TITLE
update battery storage estimate for CA-AB

### ISSUE THREAD

**Issue by pbubik** [electricitymap/electricitymap-contrib#3279]
Can we please make the following changes in CA-AB?

1. Unknown should describe source as "Dual fuel, coal/gas assumes 50/50"
2. Hydro Storage (this alone is an unfortunate name - should be Pumped Storage - to differentiate from storage in large hydro reservoirs that is not pumped) - should read 0MW (rather than "?") until Canyon Creek is commissioned. It IS 0MW in Alberta at this time.
3. Battery Storage of 597g/kWh isn't a good estimate. The mix has changed significantly since 2017. Coal was reduced, wind and solar was added. Can we use 2020 average GHGs? They could be teased out of this report: https://aeso.ca/assets/Uploads/2020-Annual-Market-Stats-Final.pdf page 16, figure 16 available here: https://aeso.ca/market/market-and-system-reporting/annual-market-statistic-reports/ 
Coal 39% of energy, gas 46%, wind, 11%, hydro+solar 3%... ergo 2020 average is 547g/kWh
4. Nuclear shoud read 0MW rather than "?" - there is 0MW capacity. Source is http://ets.aeso.ca/ets_web/ip/Market/Reports/CSDReportServlet?beginDate=&endDate=&contentType=html 
5. Geothermal should read 0MW rather than "?" - there is 0MW capacity. Source is http://ets.aeso.ca/ets_web/ip/Market/Reports/CSDReportServlet?beginDate=&endDate=&contentType=html
6. Oil should read 0MW rather than "?" - there is 0MW capacity. Source is http://ets.aeso.ca/ets_web/ip/Market/Reports/CSDReportServlet?beginDate=&endDate=&contentType=html

Thank you!

**Comment by jarek** [comment]
note to self mostly, a source for unknown being 50/50 is https://github.com/tmrowco/electricitymap-contrib/pull/3189

**Comment by jarek** [comment]
For point 2, Electricity Map maintainers would have to do the data pull for battery storage average.

I made a PR for the other points.

**Comment by pbubik** [comment]
> For point 2, Electricity Map maintainers would have to do the data pull for battery storage average.
> 
> I made a PR for the other points.

@jarek I am not sure I understand... why would "maintainers have to do a data pull for battery storage average" to show pumped hydro is 0MW capacity? Can you please clarify? 
In Alberta, there is no pumped storage currently built. Can we just show the pumped storage capacity is 0MW?

**Comment by jarek** [comment]
Sorry! That should have read "For point 3, Electricity Map maintainers would have to do the data pull for battery storage average."

So your point 1, 2, 4, 5, 6 are addressed in the PR (now merged and hopefully deployed sometime soon). Point 3 needs someone else to help.

**Comment by KabelWlan** [comment]
This has been fixed with #3871.

**Comment by jarek** [comment]
Thanks! I'll close, then, but feel free to reopen if needed
