### ISSUE TITLE
Ireland (IE) data not displayed on electricity map

### ISSUE THREAD

**Issue by Wexford1** [electricitymap/electricitymap-contrib#3383]
Hi, for the past several days no Ireland data has been displayed on electricity map.  Can Ireland be restored?
Thanks in advance,
Daniel

**Comment by skovhus** [comment]
Thanks for creating this issue.

The eirgrid API has been very unstable. :/ 

`poetry run test_parser 'IE' production` seems to work locally for me, so maybe the data will be back up soon.                                             

```
2021-09-13 14:48:26,459 DEBUG    urllib3.connectionpool         Starting new HTTPS connection (1): transparency.entsoe.eu:443
2021-09-13 14:48:27,498 DEBUG    urllib3.connectionpool         https://transparency.entsoe.eu:443 "GET /api?documentType=A75&processType=A16&in_Domain=10YIE-1001A00010&periodStart=202109111200&periodEnd=202109131200&securityToken=f0c774a8-814c-4f9a-a1d3-171e95b50b4b HTTP/1.1" 200 None
Parser result:
[{'datetime': datetime.datetime(2021, 9, 13, 10, 0, tzinfo=tzutc()),
  'production': {'biomass': None,
                 'coal': 754.0,
                 'gas': 950.0,
                 'geothermal': None,
                 'hydro': 0.0,
                 'nuclear': None,
                 'oil': 473.0,
                 'solar': None,
                 'unknown': 0.0,
                 'wind': 673.0},
  'source': 'entsoe.eu',
  'storage': {'hydro': -7.0},
  'zoneKey': 'IE'},
 {'datetime': datetime.datetime(2021, 9, 13, 10, 30, tzinfo=tzutc()),
  'production': {'biomass': None,
                 'coal': 746.0,
                 'gas': 942.0,
                 'geothermal': None,
                 'hydro': 0.0,
                 'nuclear': None,
                 'oil': 466.0,
                 'solar': None,
                 'unknown': 0.0,
                 'wind': 759.0},
  'source': 'entsoe.eu',
  'storage': {'hydro': -5.0},
  'zoneKey': 'IE'},
 {'datetime': datetime.datetime(2021, 9, 13, 11, 0, tzinfo=tzutc()),
  'production': {'biomass': None,
                 'coal': 692.0,
                 'gas': 951.0,
                 'geothermal': None,
                 'hydro': 0.0,
                 'nuclear': None,
                 'oil': 465.0,
                 'solar': None,
                 'unknown': 0.0,
                 'wind': 808.0},
  'source': 'entsoe.eu',
  'storage': {'hydro': -5.0},
  'zoneKey': 'IE'},
 {'datetime': datetime.datetime(2021, 9, 13, 11, 30, tzinfo=tzutc()),
  'production': {'biomass': None,
                 'coal': 699.0,
                 'gas': 959.0,
                 'geothermal': None,
                 'hydro': 0.0,
                 'nuclear': None,
                 'oil': 470.0,
                 'solar': None,
                 'unknown': 0.0,
                 'wind': 810.0},
  'source': 'entsoe.eu',
  'storage': {'hydro': -5.0},
  'zoneKey': 'IE'}]
---------------------
took 1.10s
min returned datetime: 2021-09-13T10:00:00+00:00 UTC
max returned datetime: 2021-09-13T11:30:00+00:00 UTC  -- OK, <2h from now :) (now=2021-09-13T12:48:27.536569+00:00 UTC)
```

**Comment by Wexford1** [comment]
That was a fast response!
Can you speculate as to why the EirGrid data stream is unstable?  Is this
normal, or was EirGrid more stable in the past?

**Comment by pierresegonne** [comment]
The IE parser is still very unstable and currently down. Just noting that Adrian Stroie tried the following:

```curl "http://smartgriddashboard.eirgrid.com/DashboardService.svc/stats?area=CO2Stats&region=ROI"
{"ErrorMessage":null,"LastUpdated":"06-Nov-2021 17:49:00","Rows":[{"EffectiveTime":"06-Nov-2021 17:45:00","FieldName":"LATEST_EMISSIONS","Region":"ROI","Value":1023},{"EffectiveTime":"06-Nov-2021 17:45:00","FieldName":"LATEST_INTENSITY","Region":"ROI","Value":226},{"EffectiveTime":"06-Nov-2021 12:00:00","FieldName":"MIN_INTENSITY_TODAY","Region":"ROI","Value":178}],"Status":"Success"}
```

```curl "http://smartgriddashboard.eirgrid.com/DashboardService.svc/stats?area=GenerationStats&region=ROI"
{"ErrorMessage":null,"LastUpdated":"06-Nov-2021 18:00:00","Rows":[{"EffectiveTime":"06-Nov-2021 18:00:00","FieldName":"LATEST_GENERATION","Region":"ROI","Value":4273},{"EffectiveTime":"06-Nov-2021 18:00:00","FieldName":"NET_IMPORT_PCT","Region":"ROI","Value":1.48},{"EffectiveTime":"06-Nov-2021 18:00:00","FieldName":"RENEWABLE_GENERATION_PCT","Region":"ROI","Value":53.77},{"EffectiveTime":"06-Nov-2021 18:00:00","FieldName":"THERMAL_GENERATION_PCT","Region":"ROI","Value":44.75}],"Status":"Success"}
```

Which shows that Eirgrid is returning some data, but that we do not ingest it at the moment:

```curl 'https://api.co2signal.com/v1/latest?countryCode=IE' -H 'auth-token: mytoken'
{"_disclaimer":"This data is the exclusive property of Tomorrow and/or related parties. If you're in doubt about your rights to use this data, please contact hello@tmrow.com","status":"ok","countryCode":"IE","data":{"fossilFuelPercentage":null},"units":{"carbonIntensity":"gCO2eq/kWh"}}:~
```

**Comment by andys73** [comment]
Just to mention that the source of that data is from the urls below and are directly from Eirgrid (got the urls from web page requests).

curl "http://smartgriddashboard.eirgrid.com/DashboardService.svc/stats?area=CO2Stats&region=ROI"

curl "http://smartgriddashboard.eirgrid.com/DashboardService.svc/stats?area=GenerationStats&region=ROI"

**Comment by andys73** [comment]
this is still not working in CO2 signal and data show unavailable on the co2 signal map. Shall you change the data pull directly from the above urls?

**Comment by corradio** [comment]
Note we also have this issue open: https://github.com/electricitymap/electricitymap-contrib/issues/2339 and this PR: https://github.com/electricitymap/electricitymap-contrib/pull/2916
Also note that the current parser is ENTSOE and that the EIRGRID parser (smartgriddashboard.eirgrid.com) only seems to display a value averaged over the last 24hrs:

![image](https://user-images.githubusercontent.com/1655848/147767680-e590cf67-c563-4a45-884c-43e8e6b24e53.png)

**Comment by brandongalbraith** [comment]
Data for Ireland appears to be flowing again at the moment.

![Screen Shot 2022-01-12 at 9 43 56 AM](https://user-images.githubusercontent.com/350893/149161966-b057adde-35ce-4078-9dab-168179c0eda6.png)

**Comment by andys73** [comment]
Great stuff hope it stays up and running :)

**Comment by Wexford1** [comment]
Yes, it is!  Thanks for the information
Regards,
Daniel

**Comment by skovhus** [comment]
I'm really happy that we can close this issue now. Thanks for all the input. :)

**Comment by Wexford1** [comment]
Hi, yesterday the Irish statistics were available, today they are missing
again!
Regards,
Daniel

**Comment by brandongalbraith** [comment]
@Wexford1 Looks like the data is flowing again within the last few hours, ENTSOE provided IE data is a bit unstable unfortunately.

**Comment by CreateYourAccount-username** [comment]
There seems to be a big difference between the electricityMap for Ireland and the EirGrid website.
For example at 06:00 today: electricityMap was 575 g/kWh and EirGrid 432 g/KwH. At 12:00 today electricityMap was 534 g/kWh and EirGrid 408 g/kWh.

**Comment by brandongalbraith** [comment]
@CreateYourAccount-username https://github.com/electricitymap/electricitymap-contrib/issues/3383#issuecomment-1003087224
