### ISSUE TITLE
Adding New Brunswick (NB Power)

### ISSUE THREAD

**Issue by Patrick-Poitras** [electricityMap/electricitymap-contrib#3435]
Hello,

I'm not sure I'm doing this right, but I wanted to add the data for New Brunswick (Canada). The entire electricity grid is run by a Crown Corporation called NB Power.

NB Power publishes an annual report every year. The latest report was published in July 2021 and is available here: https://www.nbpower.com/media/1490819/2020-21_annual_report_en_ia.pdf

The statistics section has a few breakdowns of the methods of production. 

I'm willing to input this data into something, but I don't know where in the code the data is stored.

Thanks!

**Comment by Lucadam64** [comment]
https://tso.nbpower.com/Public/en/SystemInformation_realtime.asp

Cette adresse est intéressante
