### ISSUE TITLE
Occasionally crash when using country panel

### ISSUE THREAD

**Issue by piotrek124-1** [electricitymap/electricitymap-contrib#3438]
Sometimes when I am browsing country panel website crashes with error as below:
![error](https://user-images.githubusercontent.com/66417442/136672996-f0431f2f-e5ff-4569-8895-4cea83aec4e6.png)

**Comment by dougfabris** [comment]
I'm not able to reproduce this issue, could you provide more details @piotrek124-1 ?

**Comment by madsnedergaard** [comment]
This seems related to the old translations approach so I think it's safe to close now. Please reopen if @piotrek124-1 or anyone else can still reproduce it :)
