### ISSUE TITLE
firefox 93.0 doesn't load webfont icons

### ISSUE THREAD

**Issue by bernieEV** [electricityMap/electricitymap-contrib#3446]
I found text labels "close" in the top-right corner of the first popup window, the click with left-button on mouse works.
I found text label "drop_down", "arrow_back", "arrow_drop" for the country details on the left side.
the action with the left-button of the mouse works.
there is just a library missing for the correct presentation of the icon picture. what library ?
my WEBclient is firefox 93.0 on GNU/Linux platform Ubuntu 20.04 LTS

**Comment by jarek** [comment]
That sounds like some webfonts didn't load. If you reload the page, do the icons appear?

It doesn't happen for me on Firefox 92.0 on a frankenstein Xubuntu 18.04 LTS (Bionic). I'll report back if I get an upgrade to 93.0.

![icons on firefox 92 0 on xubuntu 18 04](https://user-images.githubusercontent.com/47415/137419584-4d01f762-2349-4962-9884-8e4255507eec.png)

**Comment by bernieEV** [comment]
the solution is inside firefox WEBbrowser config
settings -> General -> Language and Appearence -> Advanced
TICK "Allow pages to choose their own fonts, instead of your selections above"

**Comment by madsnedergaard** [comment]
Great! (and also weird if it's off by default)

I'll close this issue as it's resolved :)
