### ISSUE TITLE
Dubai, United Arab Emirates

### ISSUE THREAD

**Issue by TheOtherNeo** [electricitymap/electricitymap-contrib#3447]
I found this link to the API for Dubai Data. It provides data for the traditional power plants as well as a key to the solar plants. Data is only monthly it seems and updated weekly from what I see.

[https://www.dubaipulse.gov.ae/data/dewa-consumption/dewa_gross_power_generation_mwh-open-api](url)

**Comment by IV1T3** [comment]
The power grid of the UAE is split into 4 regions according to the National Data Platform of the UAE Ministry of Energy & Infrastructure [bayanat.ae](https://data.bayanat.ae/en_GB/dataset/installed-generating-capaciy-for-electricity/resource/c8e70516-2f90-4502-968c-54712572ea72) as of 2017.

- Department of Energy Abu Dhabi - 16622 MW - https://www.doe.gov.ae/en
- Dubai Electricity & Water Authority - 10200 MW - https://www.dewa.gov.ae/en
- Sharjah Electricity and Water Authority - 2846 MW - https://www.sewa.gov.ae/en/
- Federal Electricity and Water Authority - 703 MW - https://etihadwe.ae/en/pages/default.aspx

**Comment by IV1T3** [comment]
Found a somewhat duplicate issue: #3190

**Comment by Kongkille** [comment]
Thanks for the overview!

I'm closing this issue and adding to our overview as it is not currently possible to build a real-time parser given the data provided here.
If you find new information that might help us get it done, please comment and reopen the issue [when a parser is buildable](https://github.com/electricityMap/electricitymap-contrib/wiki/Technical-requirements-for-parser-data) :)

**Comment by wheelsonrentdubai** [comment]
That’s really interesting! I didn’t know Dubai shared such detailed data about power generation. It’s great for people who like studying clean energy trends. By the way, when I visited recently, I had to [Rent a Car in Dubai](https://wheelsonrent.ae/), and exploring the city while seeing those solar projects up close was amazing.

**Comment by wheelsonrentdubai** [comment]
Interesting discussion here. I like seeing people work together to improve data accuracy and make the project more useful for everyone. Small updates like these can really help users in the long run. Even businesses like a [corporate gift supplier Dubai](https://corporategiftssuppliers.ae/) can learn from communities that focus on quality and improvement. Great work by everyone involved!
