### ISSUE TITLE
Data for Hong Kong 🇭🇰 

### ISSUE THREAD

**Issue by gwpicard** [electricitymap/electricitymap-contrib#3457]
We want to add data for Hong Kong.

Given a report from the [Environmental Bureau of the HK government](https://www.enb.gov.hk/tc/about_us/policy_responsibilities/energy.html), we know that electricity is mainly supplied by two companies:
1. China Light and Power Company Limited (CLP)
2. Hongkong Electric Company Limited (HK Electric)

We have some national statistics available at https://www.censtatd.gov.hk/en/EIndexbySubject.html?pcode=B1010002&scode=460, and it's also possible but a little hard to find some from CLP and HK electric.

It would be great to find some real-time generation sources, or more data and stats in general.

**Comment by IV1T3** [comment]
An API is also available under: https://www.censtatd.gov.hk/api/get.php?id=127&lang=en&param=N4IgxgbiBcoMJwJqJqAjDEAGHu+4GZ9iScQAaEAfQBcrMsLqAHe6bEAX0oFkfUQGdlXqVabDmNYMulAKIAbAKZgqAVwDOSgE60AnsyUChIAGpNxmDFIkZO3EBqiwWEgExNFKmAG0QAJQBDAHcqABUqACsAezUqADsQAF0HBRgabTUlTiA

A description of the API can be found using the same link as above (https://www.censtatd.gov.hk/en/web_table.html?id=127#) and clicking on the "API" button on the top.

**Comment by alixunderplatz** [comment]
I remembered having seen some real-time solar data in the last years, and I managed to re-find it :D 
Real-time data for a single 0.8MW wind turbine in HK (probably the only one that is installed in HK?) near Lamma Power Station (LPS) ...
https://www.hkelectric.com/en/our-operations/lamma-wind-power-station/real-time-operation
... and for a nearby 1MW solar farm
https://www.hkelectric.com/en/our-operations/solar-power-system/real-time-operation

However, the nearby fossil Lamma power station seems to have 3617 MW installed capacity and just outruns solar+wind^^

![image](https://user-images.githubusercontent.com/25743609/151802431-d14108a1-0045-43b9-bf52-1e2023079c61.png)

![image](https://user-images.githubusercontent.com/25743609/151802588-031e7066-dc92-41e6-a74a-0b898eae0527.png)

Unfortunately, no more info on recent load or fossil output is give, although there is an "HK electric open data" site:
https://www.hkelectric.com/en/our-operations/open-data

**Comment by Kongkille** [comment]
Thanks for the input here

I'm closing this issue for now and referring to our main issue for missing countries, if anyone finds any other data sources please place them in this issue!

**Comment by dessonchan** [comment]
Found that HK Electric has open some of the data via data.gov.hk, maybe can help to improve the estimation. But as I know CPL and HK Electric are two separated grid.

Fuel Mix Generation Data:
https://data.gov.hk/en-data/dataset/hkelectric-cs_cs-fuel-mix-generation-data/resource/6f24655c-d3a9-4a85-90ce-67b0af9e48f7

Renewable Energy Generation Amount (kWh) by Renewable Energy Type:
https://data.gov.hk/en-data/dataset/hkelectric-cs_cbd-renewable-energy-generation-by-renewable-energy-type/resource/6e64dac6-4d92-4e62-8c6e-6381b2cdcec3

**Comment by jarek** [comment]
The "Fuel Mix Generation Data" has a date picker that allows selecting individual days, but the data is actually half-yearly. This is the CSV you get:

```
﻿Year 年,Period 時期,Gas (GWh) 燃氣(百萬度),Coal & oil (GWh) 燃煤及燃油(百萬度),Renewable Energy (GWh) 可再生能源(百萬度),Total Electricity Sent Out (GWh) 總輸出電量(百萬度)
2022,First Half 上半年,2455,2187,3,4645
2021,Second Half 下半年,2898,2838,3,5739
2021,First Half 上半年,2281,2694,3,4978
```

The "Renewable Energy Generation Amount" is monthly, but most recent data is for mid-2022:

```
Year 年	Month 月	Solar Photovoltaic 太陽能光伏	Wind Power 風能
2022	6	591,770	50,481
2022	5	583,863	66,725
2022	4	674,581	62,367
2022	3	538,981	71,164
2022	2	333,634	102,578
2022	1	375,219	57,925
2021	12	399,236	70,060
2021	11	488,688	53,056
2021	10	425,260	120,056
2021	9	584,288	37,433
2021	8	470,936	29,732
2021	7	514,343	58,432
2021	6	365,298	72,464
2021	5	481,269	53,472
2021	4	369,107	98,057
2021	3	340,210	81,726
2021	2	321,173	71,642
2021	1	284,322	73,094
```
