### ISSUE TITLE
La Réunion (RE) 🇫🇷 : data error

### ISSUE THREAD

**Issue by HugoFR13** [electricityMap/electricitymap-contrib#3461]
- Zone: https://app.electricitymap.org/zone/RE
- Data set : https://opendata-reunion.edf.fr/explore/dataset/prod-electricite-temps-reel/information/

1/ The current mix doesn't show fossil power plants production (coal and gasoil). The data suddenly disapeared few weeks ago. 
2/ "Gas" is used to name the heavy oil combustion turbines production : it is a mistake as local combustion turbine only use heavy oil and not natural gas (CO2 emissions are not the same).

Thank you
@PETILLON-Sebastien

**Comment by KabelWlan** [comment]
#3472 solved this issue issue.

**Comment by madsnedergaard** [comment]
Great, thanks @KabelWlan!
