### ISSUE TITLE
Ontario (Canada) real-time data is not at all representative of the normal trend

### ISSUE THREAD

**Issue by GHbubba77** [electricityMap/electricitymap-contrib#3596]
Not sure where they get your numbers from, but Ontario's (Canada) energy mix is nowhere near what the app states (Natural Gas appearing to be a huge component).  Natural Gas (thermal) power is only a peak-time generating capacity and is typically around 5% of the total, with the lion's share being nuclear and the rest hydro.  

See: https://files.ontario.ca/q1_oer_electricity_monthly-energy-grid-output-by-fuel-type_2.jpg

I suspect the data is calculating ALL available natural gas generation capacity, which is essentially NEVER used.

**Comment by r24mille** [comment]
Data is from the IESO. Numbers from Electricity Map agree with the IESO's own, similar graphs.

https://ieso.ca/en/Power-Data

**Comment by GHbubba77** [comment]
> Data is from the IESO. Numbers from Electricity Map agree with the IESO's own, similar graphs.
> 
> https://ieso.ca/en/Power-Data

Yes, at the moment, it seems that hydro power is very low and natural gas is picking-up the slack.  But the overarching question is what is the purpose of the map for the people that view it?  I'm sure that the majority won't appreciate that Ontario's electricity mix at this EXACT moment is not at all representative of the normal trend and is essentially misrepresenting real-time data as a potential source of a handy, utterly incorrect, "quotable factoid".  

Data, without proper context, is misleading and essentially useless.

Follow this link and read: "Yearly Energy Output by Fuel Type"

- https://ieso.ca/en/Power-Data/Supply-Overview/Transmission-Connected-Generation

**Comment by jarek** [comment]
I've updated the issue title to reflect the claim being discussed

**Comment by jarek** [comment]
> Yes, at the moment, it seems that hydro power is very low and natural gas is picking-up the slack. But the overarching question is what is the purpose of the map for the people that view it? 

It is, in fact, real-time climate impact of electricity generation.

You can find this in the tutorial shown when first loading https://app.electricitymap.org/zone/CA-ON (you can open it in Private mode to view it again):

![tutorial](https://user-images.githubusercontent.com/47415/145405914-368803a3-130d-4c4e-84a9-b6bab36ce30a.png)

and in the readme of this repository:
![readme](https://user-images.githubusercontent.com/47415/145406238-4d9b2d8a-2b19-419e-afdc-8c4ac9e61044.png)

The point of Electricity Map is exactly to be able to see times when Ontario is burning more natural gas to generate electricity. For example, if charging an electric car, you might want to wait for a time with less load and/or more wind generation. There are other sources that will show you monthly or yearly averages.

**Comment by madsnedergaard** [comment]
I think @jarek points out very well how the map works and as such I think we can close this issue, as it's seems to be a misunderstanding of the data. Feel free to re-open if you disagree, @GHbubba77 :)
