### ISSUE TITLE
I often land on blog or APi docs when clicking on link to app from electricitymap.org 

### ISSUE THREAD

**Issue by steren** [electricityMap/electricitymap-contrib#3615]
On electricitymap.org, I click the "It now lives at app.electricitymap.org" link, but I land on the blog or the API docs.

It's because the touch targets of he top bar are overlapping with the link:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/360895/147028869-ce8819e8-f3e5-478d-af33-a0dd0f06239a.png">

**Comment by jarek** [comment]
This also happens to me, I thought I suddenly couldn't aim my mouse :laughing:

**Comment by corradio** [comment]
Good catch, thanks for raising @steren

**Comment by madsnedergaard** [comment]
Whoops, thanks for pointing it out - missed it as I usually have DevTools open on the side (and the padding here was using `vw`) 😅 

I've fixed it and deployed a new version now.
