### ISSUE TITLE
Spain capacity upgrade 

### ISSUE THREAD

**Issue by lvm1** [electricitymap/electricitymap-contrib#3618]
Good morning, 
I have tried a couple of days to update the production capacity of Spain, and it seems that the changes are registered but then they do not appear. I would like to know why. I leave the data in case someone is encouraged to update them, and the source from which they come (national operator of the electrical network). 

 "capacity": {
      "biomass": 1489,
      "coal": 3523,
      "gas": 33545,
      "geothermal": 0,
      "hydro": 17092,
      "hydro storage": 5645,
      "nuclear": 7117,
      "oil": 8,
      "solar": 16318,
      "unknown": 402,
      "wind": 27567

https://www.ree.es/es/datos/generacion/potencia-instalada?start_date=2021-12-01T00:00&end_date=2021-12-31T23:59&time_trunc=month&systemElectric=peninsular

![imagen](https://user-images.githubusercontent.com/96241527/147217714-f6ef9c4c-8f6d-4366-8831-c6dbb9fa5c8b.png)

![imagen](https://user-images.githubusercontent.com/96241527/147217521-ece864ae-07b3-4b0d-b904-c4b6973cd8cc.png)
@KabelWlan 

Thank you.

**Comment by KabelWlan** [comment]
Hi @lvm1 
Thank you for updating the capacities. You need to create a pull request. This can be done here:
![Unbenannt](https://user-images.githubusercontent.com/49598085/147252533-637eb306-7f82-4393-bfe2-7ee5449bfca3.png)
(I used my example of updating Bolivias capacities but it looks the same for your updates as well.) 

Afterwards you can name the pull request, give a short description of what you did and then click again on "create pull request" and you're done with your first contribution :).

**Comment by lvm1** [comment]
Thanks a lot! I'll try.

**Comment by KabelWlan** [comment]
This could be closed since #3644 updated the capacities with more recent data.
