### ISSUE TITLE
Add Saskatchewan, Canada (CA-SK) consumption

### ISSUE THREAD

**Issue by r24mille** [electricitymap/electricitymap-contrib#3633]
I tried to get this discussion going in #3587, but Electricity Map contributors seem to be more conversational in issues than in PRs :) So I'll open an issue for discussion with some of the content from that PR.

The following page shows a System Load widget in megawatts https://www.saskpower.com/Our-Power-Future/Our-Electricity/Electrical-System/System-Map It makes an AJAX call to https://www.saskpower.com/ignitionapi/Content/GetNetLoad That endpoint simply returns a number as a string. 

Without much other context, that number can be interpreted to mean "current consumption" based solely on the website widget's title, _System Load_, and the internal endpoint's name "net load". It's value is updated every ~5 minutes.

![saskpower_consumption_2021-12-10](https://user-images.githubusercontent.com/3433964/147863987-41909c45-7427-4a05-b2dd-12a9acdc2984.png)

Does a `fetch_consumption(...)` implementation provide any value to the Electricity Map organization? Even if it does mean much for the publicly viewable page?

**Comment by b-neufeld** [comment]
Hey @r24mille, some exciting news to share... Check out what SaskPower just dropped: 
https://www.saskpower.com/Our-Power-Future/Our-Electricity/Electrical-System/Where-Your-Power-Comes-From

Per the [technical requirement guidelines](https://github.com/electricitymaps/electricitymaps-contrib/wiki/Technical-requirements-for-parser-data) 24 hours may not get us a shaded colour on the map, but hopefully the data is reliable enough to incorporate.
