### ISSUE TITLE
Publish on Pypi?

### ISSUE THREAD

**Issue by martinRenou** [electricitymap/electricitymap-contrib#3687]
Is there a plan on publishing the Python code as a package on Pypi?

We are currently starting to reuse your Python parsers in order to create a similar dashboard to https://app.electricitymap.org/ but using [bqplot](https://github.com/bqplot/bqplot), [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet) and [voila](https://github.com/voila-dashboards/voila). An early draft of this work is located at https://github.com/MackyDIARRA/electricitymap_dashboard. We are planning on copying the parsers code for now, but reusing your parsers through a more official package would be nice.

cc. @MackyDIARRA @SylvainCorlay

**Comment by madsnedergaard** [comment]
Hi @martinRenou. Thanks for creating this issue and sounds like a cool project :)
While I see that this would make using the parsers externally easier, we unfortunately don't have capacity to support this use case as it would require additional tooling and securing future backwards-compatibility. 

Hope you understand and can work around this (maybe using the [releases](https://github.com/electricitymap/electricitymap-contrib/releases) to know about when there's changes?)

**Comment by martinRenou** [comment]
Thanks for your answer :) Ok, we'll find a suitable solution that does not require copying the parsers code.
