### ISSUE TITLE
No data for Germany 

### ISSUE THREAD

**Issue by Mavicgn** [electricitymap/electricitymap-contrib#3734]
Since a week, data for Germany is not available any more. please check
 thanks

**Comment by cphilc** [comment]
What / Where is the data source for Germany?

**Comment by w-flo** [comment]
See #3732

**Comment by jarek** [comment]
Data comes from ENTSO-E but is apparently missing or incorrect there. See https://github.com/electricitymap/electricitymap-contrib/issues/3732 for an issue about this. I'll close this as duplicate, but thanks for reporting.
