### ISSUE TITLE
Power-breakdown graph inconsistency

### ISSUE THREAD

**Issue by Kongkille** [electricitymap/electricitymap-contrib#3798]
## Description
The power breakdown graph for non-estimated data is always **production** whereas the graph is always **consumption** for estimated data regardless of the toggle. This can cause a lot of confusion to users. 

## Example

An example is explained in #3793. Here we see that coal and unknown are not present in the breakdown for the non-estimated data (regardless of toggling between production/consumption). It is, however, present in the estimated data because the estimated data is using the consumption-breakdown whereas the non-estimated data is always using the production-breakdown.

![image](https://user-images.githubusercontent.com/45588799/154040219-74c2a851-d2df-45f4-9a87-7ab62b8fdbf5.png)

As one can imagine, this is quite confusing to users as different breakdowns are displayed hour-to-hour.

## Solution
Switch out estimated data to use the production breakdown instead of consumption

**Comment by KabelWlan** [comment]
![2](https://user-images.githubusercontent.com/49598085/155849519-d30bb631-1ef6-4616-bd27-dc27d8859332.png)
I followed this issue for a few days. Today it was very obvious and it is significantly different to the reality. 
When there's no data for the most recent hour displayed, the estimate feature shows the emissions of the estimated value which is often off for quite a bit. In this example of Germany, the map shows 165g even though it is more likely to be around 400g.
This issue doesn't appear for all the zones I've seen it happen for Germany, Belgium, all the Norway and Denmark zones, GB, Spain, Poland and Italy.
The estimated data gets then replaced by the realtime data at around xx.45 which means that the countries have their "appropriate" color for about 15 each hour. I've also had a look on Entsoe which doesn't seem to be the problem. The reported data for the hour seems to be available. 
Maybe someone with more knowledge on how the Entsoe phraser works, can double check. I think it's weird that it happens to only a few of those Entsoe countries and not all of them.

**Comment by Kongkille** [comment]
@KabelWlan thanks for sharing. In these past weeks, I've also seen some examples where VRE is highly different from the non-estimated value. While we do mention it's an estimate, the purpose is still to be as reliable as possible, and there have been some hours in which the real-time estimate is too far off.

I'll talk to the team to see if this is an issue on the modeling side. Otherwise, there may also be avenues to look into with the Entsoe parser, as Germany especially has had some issues the last month.
