### ISSUE TITLE
Update EIA.py to use https URLs instead.

### ISSUE THREAD

**Issue by FelixDQ** [electricitymap/electricitymap-contrib#3799]
The EIA API no longer supports insecure HTTP requests, so we should update the URLs to use `https` instead.
<img width="521" alt="image" src="https://user-images.githubusercontent.com/12124251/154065730-ff26bd5a-78b5-48de-bfd0-19da61e9c2eb.png">

**Comment by FelixDQ** [comment]
@systemcatch are you able to release a new version of eiapy with https://github.com/systemcatch/eiapy/pull/23 applied or should we patch it on our end?

**Comment by systemcatch** [comment]
Hi @FelixDQ I can release a new version in the next day or two.

**Comment by FelixDQ** [comment]
Awesome, thank you!

**Comment by systemcatch** [comment]
@FelixDQ 0.1.6 has been released to pypi!
