### ISSUE TITLE
Serbia "utilizing" >1000% of hydro capacity

### ISSUE THREAD

**Issue by veqtrus** [electricitymap/electricitymap-contrib#3803]
![Screenshot](https://user-images.githubusercontent.com/3521837/154542563-3287107e-a947-4b6f-9735-5d7cb2210745.png)

**Comment by jarek** [comment]
Looks to have since been fixed. Data comes from ENTSO-E, so problem likely was on operator's side.

**Comment by madsnedergaard** [comment]
Seems like you're right, let's close it for now :)
