### ISSUE TITLE
Italy : allow to view aggregated national data

### ISSUE THREAD

**Issue by fhtino** [electricitymap/electricitymap-contrib#3816]
Currently Italy is divided in 5 regions. To better understand how globally Italy behaves, it would be vey useful to have also a whole country view, removing internal regions exchanges and having a global Italy exchanges with connected countries.

**Comment by madsnedergaard** [comment]
Hey Fabrizio, thanks for raising this :)
We agree that this would be useful, but unfortunately we cannot currently support both national and regional data sources. It's on our roadmap though and something we're super excited to work on in the not-too-far-away future :) 

I'll close this issue for now, but we'll revisit this when we start working on it.
See also similar issues for https://github.com/electricitymap/electricitymap-contrib/issues/1397 (Sweden), https://github.com/electricitymap/electricitymap-contrib/issues/3795 (Germany) and https://github.com/electricitymap/electricitymap-contrib/issues/2777 (France)
