### ISSUE TITLE
Questions and remarks on the estimated feature

### ISSUE THREAD

**Issue by KabelWlan** [electricitymap/electricitymap-contrib#3821]
First of all, the estimated feature is really cool and I like it. I think it has a huge potential!

While using it for a while now, I found some things I wanted to ask:

- Why are some of the US zones estimated and others aren't? Is there a specific reason?

- Also, I wanted to remark that US-NW-WACM reports a steady 8.29 GW of pumped hydro generation. That's impossible.
![1](https://user-images.githubusercontent.com/49598085/155850833-59ce1079-8c3b-4deb-ad06-7007e311e9c4.png)

- I don't have a screenshot, but I've noted that the Netherlands reported over 100% wind generation quite often in the last few days when it was windy. [Energieopwek.nl](https://energieopwek.nl/) reported about 500 MW less. However, they report more solar generation (up to 2.5 times more). Maybe you could have a look at that sometime. 
I think it's cool how you "fixed" the incomplete data, it's not perfect but amazing how well it already works.

- When the tool uses the "Time Slicer Average" things like this come out:
![3](https://user-images.githubusercontent.com/49598085/155851133-ecb0a2be-f54a-4056-87bf-41886ad33a88.png)
While the total generation is estimated very well, the production break down is jumpy. A possible approach could be looking at the last available generation break down and then "filling/estimating it with the same percentages adjusted to the estimated total generation." I'm sure you guys will find a solution to this as well. It's often seen in the US-MIDA-PJM zone as well.

- The flickering issue has already been mentioned in #3807 so I don't comment any further on that. 

- I also wanted to mention that I'm amazed how well the estimation works for Chile. You can't even see a difference between estimated and real data.

**Comment by madsnedergaard** [comment]
cc @pierresegonne :)

**Comment by pierresegonne** [comment]
> Why are some of the US zones estimated and others aren't? Is there a specific reason?

We currently don't produce estimates for all of electricityMap's zones. The choice of zones that are estimated depends on available data, data quality and requests by our customers and partners. The current list consists of:

```
    "AT",  # Austria
    "BE",  # Belgium
    "CL-SEN",  # Chile
    "DE",  # Germany
    "DK-DK1",  # Denmark
    "DK-DK2",  # Denmark
    "FI",  # Finland
    "GB",  # Great Britain
    "IE",  # Ireland
    "NL",  # Netherlands
    "NO-NO1",  # Norway
    "NO-NO2",  # Norway
    "NO-NO3",  # Norway
    "NO-NO4",  # Norway
    "NO-NO5",  # Norway
    "SE",  # Sweden
    "SG",  # Singapore,
    "TW",  # Taiwan
    "US-CAR-DUK",  # Duke Energy Carolinas
    "US-CAR-SC",  # South Carolina Public Service Authority
    "US-CENT-SWPP",  # Southwest Power Pool
    "US-MIDA-PJM",  # Pjm Interconnection, Llc
    "US-MIDW-MISO",  # Midcontinent Independent Transmission System Operator, Inc.
    "US-NW-BPAT",  # Bonneville Power Administration
    "US-NW-NEVP",  # Nevada Power Company
    "US-SE-SOCO",  # Southern Company Services, Inc. - Trans
    "US-TEN-TVA",  # Tennessee Valley Authority
    "US-TEX-ERCO",  # Electric Reliability Council Of Texas, Inc.
     "AUS-NSW",  # New South Wales, Australia
    "AUS-VIC",  # Victoria, Australia
    "BR-CS",  # Central Brazil
    "CA-ON",  # Ontario
    "ES",  # Spain
    "FR",  # France
    "IT-SIC",  # Sicily, Italy
    "IT-SO",  # South, Italy
    "IT-CSO",  # Central South, Italy
    "IT-SAR",  # Sardinia, Italy
    "IT-CNO",  # Central North, Italy
    "IT-NO",  # North, Italy
    "PL",  # Poland
    "US-CAL-BANC",  # Balancing Authority Of Northern California
    "US-CAL-CISO",  # California Independent System Operator
    "US-CAL-LDWP",  # Los Angeles Department Of Water And Power
    "US-FLA-FPL",  # Florida Power & Light Company
    "US-NW-PACE",  # Pacificorp - East
    "US-NW-PGE",  # Portland General Electric Company
    "US-NW-PSCO",  # Public Service Company Of Colorado
    "US-NW-WACM",  # Western Area Power Administration - Rocky Mountain Region
    "US-SW-SRP",  # Salt River Project
    "UY",  # Uruguay
```

> Also, I wanted to remark that US-NW-WACM reports a steady 8.29 GW of pumped hydro generation. That's impossible.

Indeed, I'll create an issue to resolve this problem.

> I've noted that the Netherlands reported over 100% wind generation 

Please if you see this happen again let us know, as this should obviously not happen. The very design of the estimation model for `NL` should prevent that. Thanks for the compliment! We know that this model is far from perfect, as it is our first stab at predicting accurately the mix of a given zone. Now that the infrastructure that allows the inclusion of these estimates is in place, we will be able to focus in the future on improving the models themselves. We're still a small team, so it might take some time :)

> While the total generation is estimated very well, the production breakdown is jumpy

We are aware of this issue, and already have a solution for this in the box, we nevertheless need to run some final verification of the updated model before making it the new official version. 

> I also wanted to mention that I'm amazed how well the estimation works for Chile. You can't even see a difference between estimated and real data.

👏👏👏👏
