### ISSUE TITLE
Is there a possibility to see the primary energy consumption of the countries?

### ISSUE THREAD

**Issue by klacol** [electricitymap/electricitymap-contrib#3835]
Hi,

this project is really great. I look on the app every day to learn about the principles of the production of electricity.

I wonder, if anybody knows, if there are similar projects/sources to show the primary energy consumption of the countries. That would include also the energy for heating, traffic, industry, etc. that is not using electricity.

**Comment by Kongkille** [comment]
Heyo,

[IEA.org](https://www.iea.org/data-and-statistics) has a ton of this data available for free in chart format. 

This is a great question for our Slack channel as well, as some people may have other interesting sources :)

[Slack](https://slack.tmrow.com/)
