### ISSUE TITLE
NYISO real time data

### ISSUE THREAD

**Issue by steren** [electricitymap/electricitymap-contrib#3855]
Just sharing that New York ISO has a real time dashboard: https://www.nyiso.com/real-time-dashboard

I have not checked if this is new or if electricitymap is already using it. Feel free to close if so.

**Comment by jarek** [comment]
Thanks! We do use it

https://app.electricitymap.org/zone/US-NY-NYIS

https://github.com/electricitymap/electricitymap-contrib/blob/master/parsers/US_NY.py
