### ISSUE TITLE
A single source for Canadian installed capacities

### ISSUE THREAD

**Issue by kruschk** [electricitymap/electricitymap-contrib#3859]
[Natural Resources Canada lists each province's installed capacities](https://www.nrcan.gc.ca/energy/electricity-infrastructure/electricity-canada/canada-electric-reliability-framework/albertas-electric-reliability-framework/18826), including a breakdown based on generation type. At present, the figures are from 2014 to 2016, depending on the province. Despite being a bit old, would it be an improvement to use these data, rather than the current medley of sources (i.e., provincial operators and Wikipedia)? If so, I'd be happy to work on a PR!

**Comment by madsnedergaard** [comment]
Hey @kruschk, thanks for sharing! While it would be good with a single source, the 6 year delay makes it very hard to justify. I think it's better to have more accurate data, with the tradeoff that verifying the source is a bit more messy :)

**Comment by kruschk** [comment]
@madsnedergaard Thanks for the feedback! I thought that might be the case, but wanted to suggest it anyway. Maybe I'll go try my hand at fixing a parser instead!

**Comment by madsnedergaard** [comment]
Thanks for the suggestion :D 
And that sounds awesome! 💪
