### ISSUE TITLE
Tasmania (AUS-TAS) should include power imports

### ISSUE THREAD

**Issue by maxfire2008** [electricitymap/electricitymap-contrib#3876]
[Tasmania](https://app.electricitymap.org/zone/AUS-TAS) should include the fossil fuel imports from Victoria and other states https://www.aemo.com.au/energy-systems/electricity/national-electricity-market-nem/data-nem/data-dashboard-nem

**Comment by jarek** [comment]
Thank you for noting! This is actually because all of our Australian import/export data is broken - see https://github.com/electricitymap/electricitymap-contrib/issues/3689 for that issue
