### ISSUE TITLE
New data sweden

### ISSUE THREAD

**Issue by Henrik575** [electricitymap/electricitymap-contrib#3919]
Hi,

The following link leads to new data for sweden

https://pxexternal.energimyndigheten.se/pxweb/sv/N%c3%a4tanslutna%20solcellsanl%c3%a4ggningar/N%c3%a4tanslutna%20solcellsanl%c3%a4ggningar/EN0123_1.px/table/tableViewLayout2/?loadedQueryId=1f5d3f27-504d-4668-b762-9b7c9e4d6c7c&timeType=from&timeValue=0

**Comment by VIKTORVAV99** [comment]
Oh I was waiting for this but expected it to be published tomorrow.

I'll get a PR ready asap.

**Comment by Henrik575** [comment]
Thanks!

ons 30 mars 2022 kl. 09:54 skrev Viktor Andersson ***@***.***
