### ISSUE TITLE
Several zones/regions missing carbon intensity in production mode

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymap/electricitymap-contrib#3925]
When switching the map to production mode East Denmark (DK-DK2) have no carbon intensity.

This happens both when the data is estimated and live and as you can see on the image below it appears like all other data is correct. 
![image](https://user-images.githubusercontent.com/30777521/161055684-8512ef9a-fecb-465b-b793-a279b7d3b136.png)
_Screenshot taken at roughly 12:35 UTC_
 
**Note:** This is only happening when switching to production mode on the map, consumption mode appears calculate the carbon intensity correctly.

**Comment by madsnedergaard** [comment]
Hmm, weird 🤔 
Especially since `DK-DK1` is fine, and both zones use ENTSO-E...

**Comment by gwpicard** [comment]
This seems to be happening with Croatia too...

<img width="483" alt="Screenshot 2022-04-01 at 10 23 09" src="https://user-images.githubusercontent.com/7591224/161224935-4aabd149-392c-489a-8eeb-a178ecb825dc.png">


<img width="477" alt="Screenshot 2022-04-01 at 10 23 26" src="https://user-images.githubusercontent.com/7591224/161224978-23c44fd0-21fb-4d52-b3d1-f81b0a512bcc.png">

**Comment by VIKTORVAV99** [comment]
I found several more affected regions:

- Bornholm (DK-BHM)
- Åland Islands (AX)
- Mallorca (ES-IB-MA)
- Menorca (ES-IB-ME)
- Ibiza (ES-IB-IZ)
- Formentera (ES-IB-FO)
- Gran Canaria (ES-CN-GC)
- Fuerteventura/Lanzarote (ES-CN-FVLZ)
- Tenerife (ES-CN-TE)
- Isla de la Gomera (ES-CN-IG)
- La Palma (ES-CN-LP)
- El Hierro (ES-CN-Hi)
- King Island (AUS-TAS-KI)
- Flinders Island (AUS-TAS-FI)
- Kyūshū (JP-KY)
- Israel (IL)
- Cyprus (CY)
- Orkney Islands (GB-ORK)
- Prince Edward Island (CA-PE)
- Associated Electric Cooperative, Inc. (US-MIDW-AECI)
- Seminole Electric Cooperative (US-FLA-SEC)
- Florida Power & Light Company (US-FLA-FPL)
- Florida Municipal Power Pool (US-FLA-FMPP)
- Tampa Electric Company (US-FLA-TEC)
- El Paso Electric Company (US-SW-EPE)
- Arizona Public Service Company (US-SW-AZPS)
- Tucson Electric Power Company (US-SW-TEPC)
- Gridforce Energy Management, Llc (US-NW-GRID)
- Honduras (HN)

I think that was all affected zones plus the two zones we mentioned before.  

Irland was also affected but seems to have recovered?
![image](https://user-images.githubusercontent.com/30777521/161292151-3cbcfc4a-a26d-4201-a361-e1dd5cc03306.png)

It appears the problem is much bigger than I initially thought and it is across several different parsers.

**Note:** _Data collected at around 15:30 UTC_

**Comment by corradio** [comment]
A fix has been proposed (cc @pierresegonne @madsnedergaard )

**Comment by corradio** [comment]
This should have been fixed now. Feel free to re-open if it happens again.
