### ISSUE TITLE
Faulty link in translation page

### ISSUE THREAD

**Issue by JakeGonder** [electricitymap/electricitymap-contrib#3931]
The link at the bottom of the [translation page](https://github.com/electricitymap/electricitymap-contrib/wiki/Translating-electricitymap.org), leads to 404 not found:

> Find the translation file [here](https://github.com/tmrowco/electricitymap-contrib/tree/master/web/locales) and open it.

**Comment by VIKTORVAV99** [comment]
I have updated the wiki page; the link should now have the correct path.

This issue can now be closed.
