### ISSUE TITLE
Missing data panel for regions with data

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymap/electricitymap-contrib#3949]
There seems to be a bug where several regions that have valid data show the missing data panel.

![image](https://user-images.githubusercontent.com/30777521/162268928-3d08d215-e77e-4b0f-ad86-c9c498bf1d4e.png)
_Screenshot taken at 18:05 UTC_

Some of the affected regions are:

- Southeast Norway
- Middle Norway
- North Norway
- West Norway
- Sweden
- Poland
- Great Britan
- Central South Italy
- South Italy

**Note:** While writing this issue the regions recovered at about 18:13 UTC.

**Comment by brandongalbraith** [comment]
@VIKTORVAV99 Try quitting and reloading the browser tab or mobile app? As of this comment, the data shows as available for me in both a browser and the mobile iOS app:

![image](https://user-images.githubusercontent.com/350893/162270235-c19e11ff-cd71-41cb-a236-8740ade30e9b.png)

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 Try quitting and reloading the browser tab or mobile app? As of this comment, the data shows as available for me in both a browser and the mobile iOS app:
> 
> ![image](https://user-images.githubusercontent.com/350893/162270235-c19e11ff-cd71-41cb-a236-8740ade30e9b.png)
> 

It recovered on its on at roughly 18:13 UTC but I still thought it was worth filing a issue.
(Last line in my issue mentioned this)

**Comment by madsnedergaard** [comment]
cc @Kongkille, could this be due to the change in #3934? 🤔 
I can't reproduce it, so please do keep us updated if this happens again for anyone!

**Comment by VIKTORVAV99** [comment]
@madsnedergaard might I ask when you tried to reproduce it? (exact time)

I can reproduce it but only just after the time changes to a new hour (8:59 to 9:00 for example).

It also seems to affect regions at random.

**Comment by Kongkille** [comment]
Hmm this could very well be a bug by #3934. 

Essentially that PR decouples the state file (used to show the global map) and the history file (the details)

During testing I did not experience these issues, I am wondering whether this could be an issue with our caching logic. I'll investigate in the app-backend.

**Comment by Gazer75** [comment]
What region might be missing seem quite random. A reload can fix one region, but then another is not showing.
Clearing cache/cookie or using Ctrl+F5 doesn't seem to matter much.

**Comment by madsnedergaard** [comment]
We've found the issue: In the app-backend we're caching state and history files with an expiration of 10 minutes.
This means there's situations where those two files are not in-sync (as each zone-history file is saved to cache depending on when someone requested it), and data might be out of date. 

We're currently working on fixing this :)

**Comment by ykabusalah** [comment]
Can I have a shot at attempting to fix this issue?

**Comment by madsnedergaard** [comment]
> Can I have a shot at attempting to fix this issue?

The issue is on our backend which isn't open-source, but work is in progress :)

**Comment by Kongkille** [comment]
We just published a fix, hopefully this resolves the issue. If anyone sees it again, please reopen. Thanks for flagging!

**Comment by VIKTORVAV99** [comment]
@Kongkille how long do you think it takes for the fix to take affect? It just happened again...

**Comment by Kongkille** [comment]
Yes it unfortunately seems our changes were not enough. We'll work on getting a proper fix in ASAP.

**Comment by Kongkille** [comment]
I believe this should be closed now. Aside from an issue (unrelated to this) with ZA we now should always have sync between state and history
