### ISSUE TITLE
We should try making the frontend a completely static site

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymap/electricitymap-contrib#3986]
Like the title says we should try and make the frontend a completely static webpage (html, js, css and assets).

### Pros:
- Simplified build process.
- No need for a server to dynamically render the index.html page.
- No need for docker (depending on the deployment environment).
- Less code debt.
- Better performance as the server no longer have to generate (and compress) content.

### Cons:
- Less flexibility.
- Significant code changes.
- Might need special redirect rules on the deployment side.
  
  
Just thought I should open this so we can discuss it and coordinate what can and needs to be done in order to get it working.

**Comment by madsnedergaard** [comment]
I very much agree, we have an open issue for it here: https://github.com/electricitymap/electricitymap-contrib/issues/3837 😄

**Comment by VIKTORVAV99** [comment]
@madsnedergaard oh I thought that issue referred to something else 😅

Should I close this issue?
