### ISSUE TITLE
"No data source available" no longer shows

### ISSUE THREAD

**Issue by Kongkille** [electricitymap/electricitymap-contrib#3988]
All zones without real-time data say that the data is temporarily unavailable instead of missing completely

![image](https://user-images.githubusercontent.com/45588799/164220257-0f528993-dec2-415b-a80d-154202611e06.png)

This might be a result of #3934

**Comment by VIKTORVAV99** [comment]
This appears to only happen when it initially loads, if you move the time slider back and then forth again to the original placement "error" message goes away.
