### ISSUE TITLE
estimation on wind power seems to reference previous day

### ISSUE THREAD

**Issue by DerDakon** [electricitymap/electricitymap-contrib#4007]
The power estimation seems to just reuse (more or less) the power output done on the previous day, which can cause huge jumps in the power. I would suggest just using the last "real" wind value if no forecast from outside is available.

**Comment by madsnedergaard** [comment]
I'm not sure I understand, can you elaborate on this and provide some screenshots?

**Comment by DerDakon** [comment]
Power generation in Germany, last real data:

![elec_lasthour](https://user-images.githubusercontent.com/10909049/165566015-171d4da9-d302-47f4-a77f-c477ee65df3e.png)

Estimation for the next hour:

![elec_estimated](https://user-images.githubusercontent.com/10909049/165566042-f0240aaa-15e1-4a1d-9aba-50c4f1be4a3b.png)

Please see the huge increase in wind power. It's actually not the data from yesterday, there hasn't been much wind yesterday either. So it's probably taken from a week ago or something like that. It just does not make sense to take the wind power generation prediction from any data older than just what we have now as wind does not repeat.

**Comment by josemam** [comment]
This. The wind power prediction model (which I guess derives from what is shown [here](https://github.com/electricitymap/electricitymap-contrib/wiki/Reconstruct-Breakdown)) is sometimes way off for Spain too. This affects the carbon intensity map, which is drawn from the predicted data if no real-time data is available. For example, right now it predicts for Spain a carbon intensity slightly above half the value in the previous hour, which will probably be close to the real figure for the current hour. One week ago, it was the other way around: it estimated about double the real carbon intensity.

These examples might not be representative and there might be reasons not to do so, but a simple assumption that the wind power output will be the same as in the previous hour would have better matched the real data in those instances.

**Comment by pierresegonne** [comment]
Yes the updated model is in production now. 

As is explained in the wiki (see Mads' link above), we do take averages of previous values to compute the estimates. We know that for wind this is sub-optimal, but have not yet been able to train wind models for all zones that have estimates. We'll get there in some time, but you can see this as a WIP with incremental improvements :)
