### ISSUE TITLE
Can't click on regions on the map

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymap/electricitymap-contrib#4039]
Looks like v0.255.0 introduced a bug that made countries un-clickable (no country detail panel show up).

It's probably smart to revert the code/dependency updates in `/web` until we know the cause.

Ping @madsnedergaard.

**Comment by madsnedergaard** [comment]
Thanks @VIKTORVAV99! 😞 
I'm reverting the dependencies-update PR, super annoying that it's breaking things...

**Comment by madsnedergaard** [comment]
(I guess I should also have tested this locally, assumed minor changes wouldn't be breaking 😬)

**Comment by VIKTORVAV99** [comment]
Yep unfortunately that's how it is 🙃

I should have some time tomorrow to test a few dependancy upgrades but I will take some time to check them all.

**Comment by VIKTORVAV99** [comment]
They shouldn't have been, but if some sub dependancy didn't follow semver or we where using something incorrectly that got fixed it can happen.

Can also just be a case of miss-matched dependencies where one got updated and the other was blocked for some reason.

**Comment by madsnedergaard** [comment]
Release in progress, should be out within an hour! 
I also went through all the changed dependencies and found the cause (which seems obvious looking back): `react-map-gl` :)

**Comment by madsnedergaard** [comment]
And it's back, thanks again @VIKTORVAV99 😍
