### ISSUE TITLE
Simplify state and history files object structure

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymap/electricitymap-contrib#4049]
This discussion originally started in #4044 but as it is a separate topic I have opened this issue for further discussion.

**Comment by madsnedergaard** [comment]
I just made a small script that:
a) removes zones where all entries are empty (aka. no data available)
b) removes all null values

<img width="546" alt="Screenshot 2022-04-28 at 10 53 37" src="https://user-images.githubusercontent.com/3296643/165715765-2c810165-73ab-49f0-9912-25412206e4c4.png">

These are the raw file sizes, so before gzip and compression. This is however still a significant change from before:
<img width="307" alt="Screenshot 2022-04-28 at 10 55 01" src="https://user-images.githubusercontent.com/3296643/165716075-7f8f7a6c-b7ec-475e-9021-650f5388099c.png">

**Comment by VIKTORVAV99** [comment]
Woah that state file change is massive!

I haven't really looked into what needs to be changed in the frontend but if the structure is the same but with no empty or null values it should be pretty simple to change the frontend already without impacting the current behavior.

> b) removes all null values

Did this remove both the keys and null values or just the null values?
