### ISSUE TITLE
South Korean electricity price is off by a factor of 1000x

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymap/electricitymap-contrib#4084]
Someone reached out to us on email with the following feedback:

Just want to mention, that the electricity price in South Korea is probably off by factor of 1000x.
I believe this is due to different way to use decimal point. Great Britain and the United States are two of the few places in the world that use a period to indicate the decimal place. Many other countries use a comma instead. The decimal separator is also called the radix character. Likewise, while the U.K. and U.S. use a comma to separate groups of thousands, many other countries use a period instead, and some countries separate thousands groups with a thin space.

**Comment by MakotoNakai** [comment]
@madsnedergaard 
Can I work on this issue?

**Comment by madsnedergaard** [comment]
Yes please, that would be great! 🙌

**Comment by packagespace** [comment]
Hello, is this issue still being worked on?

**Comment by MakotoNakai** [comment]
@packagespace 
Sorry for being inactive so long.  I've been so busy these days, so you can work on this issue instead.
