### ISSUE TITLE
ElectricityMap hangs while loading when wind layer is enabled

### ISSUE THREAD

**Issue by q--** [electricitymap/electricitymap-contrib#4120]
Tried on desktop and mobile Firefox and desktop, as well as desktop Chrome, both with private browsing and without.

Tried URLs with  the parser down (https://app.electricitymap.org/zone/PR?wind=true, https://app.electricitymap.org/zone/NL?wind=true) and without (https://app.electricitymap.org/zone/GE?wind=true)

Firefox stays blank, Chrome shows the 'page is not responding' dialog after a while, and Firefox mobile shows the 'no area data' text after a while (for countries that definitely have data).

Turning on my (work) VPN doesn't change anything either.

The title on the browser tab shows up, though.

**Comment by madsnedergaard** [comment]
Damn, that's weird - thanks for reporting it! Same with solar, I'll revert latest changes :(
