### ISSUE TITLE
Corsica is exporting 100% or more of its generation to Italy because of missing Corsica-Sardinia interconnector data

### ISSUE THREAD

**Issue by q--** [electricitymap/electricitymap-contrib#4137]
Corsica was added in #3978, but for some reason the carbon-intensity isn't calculated during most of the day. (See the carbon intensity in the top left and the carbon intensity graph in the screenshot below.)

The likely cause of this is that ElectricityMap thinks it's exporting more than 100% of its generation to Italy during those times (and even when intensity *is* available, it's 'exporting' close to 100%).

![Screenshot of Corsica electricity generation in ElectricityMap](https://user-images.githubusercontent.com/2470175/168850000-7c127741-1d48-4175-8695-ce5d9b3ff223.png)

**Comment by madsnedergaard** [comment]
cc @pierresegonne, any idea why?

**Comment by VIKTORVAV99** [comment]
This appears to be the same problem as in #3925.

Not sure what is causing it since I don't know how the backend code works but I haven't seen any issue with the regions affected that time since the fix was applied.

Perhaps it's something that should be run each time a new zone is added?

**Comment by pierresegonne** [comment]
I don't have a clear answer, but I think that it probably comes down to the data not passing the sanity checks we have in the backend. This means that the data is not flowtraced for these hours, and thus no carbon intensity is produced. I'll dive a bit deeper into it.

**Comment by q--** [comment]
Hmm, I just noticed it's exporting approximately 100% of generation to Italy. Even more during  times of the day when data is grayed out. That cannot be right.

**Comment by VIKTORVAV99** [comment]
> Hmm, I just noticed it's exporting approximately 100% of generation to Italy right now. Even more (say, 138%) during times of the day when carbon intensity is grayed out. That cannot be right.

There is a missing exchange between Corsica, Sardinia and Central North Italy, that is probably why it can go above 100% at times. https://en.wikipedia.org/wiki/HVDC_Italy%E2%80%93Corsica%E2%80%93Sardinia

**Comment by pierresegonne** [comment]
Indeed we have no parser for the Corsica-Sardinia exchange.
Plus, running a quick analysis, it's quite clear that it's the fact that total exports > total production that result in no carbon intensity. 
We could: 
1. Deactivate the FR-COR->IT-CNO exchange. That would ensure that we show data for COR, but I don't like the idea of showing data that we know if false
2. Expand the FR-COR parser. Looking at https://opendata-corse.edf.fr/explore/dataset/production-delectricite-par-filiere-en-temps-reel/table/?sort=-date we can see that they provide total imports. If we combine this with the FR-COR->IT-CNO parser then we should be able to infer the FR-COR->IT-SAR exchange and solve the problem :)

**Comment by q--** [comment]
Or
3. combine FR-COR and IT-CNO into one zone by adding up their generation.


But \#2 seems best. But I wonder, is there no FR-COR<->IT-CNO data available via ENTSOE?

**Comment by q--** [comment]
Strange, the ENTSOE [grid map](https://www.entsoe.eu/data/map/) doesn't have te AC interconnector anywhere. Also, I notice there is another interconnector straight from Sardinia to the mainland, but I assume you checked the data sources you found aren't for that one.

Anyway, looks like opendata-corse is indeed the way to go

**Comment by VIKTORVAV99** [comment]
> Strange, the ENTSOE [grid map](https://www.entsoe.eu/data/map/) doesn't have te AC interconnector anywhere between Corsica and Sardinia.

I think that map only show high voltage connections, so it is possible the connection don't have a high enough voltage to make it into the map. But that is just me speculating.

> Also, I notice there is another interconnector straight from Sardinia to the mainland, but I assume you checked the data sources you found aren't for that one.

Yep that should be [this one](https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=19.05.2022+00:00|CET|DAY&border.values=CTY|10YIT-GRTN-----B!BZN_BZN|10Y1001A1001A71M_BZN_BZN|10Y1001A1001A74G&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)).


> Anyway, looks like opendata-corse is indeed the way to go

Yes defiantly, if my brain don't betray me now the function would be something like:
```
"IT-SAR->FR-COR DC" = -"IT-SAR->FR-COR AC" - "FR-COR->IT-CNO" + opendata-corse

net_"IT-SAR->FR-COR"_exchange = "IT-SAR->FR-COR DC" + "IT-SAR->FR-COR AC"
```
That can probably be simplified but yeah.

**Comment by VIKTORVAV99** [comment]
Related to #2991

**Comment by VIKTORVAV99** [comment]
ENTSO-E now (since 2022-08-03) have data on the IT-SACODC exchange between Corsica and Sardinia so it will be a simple matter of aggregating the IT-SACODC and IT-SACOAC exchange between the two zones.
