### ISSUE TITLE
Better data for NL (but probably requires a paid license again)

### ISSUE THREAD

**Issue by q--** [electricitymap/electricitymap-contrib#4139]
So the usage of Energieopwek data was discontinued due to them requiring a paid license (https://github.com/electricitymap/electricitymap-contrib/issues/3015#issuecomment-901670043).

I found this new website, [CO2Monitor](https://co2monitor.nl/energiebronnen), which splits energy generation by source &ndash; click "Stroom" near the top right &ndash; a lot better than ENTSOE (for example, it appears to account for biomass correctly). [It uses a combination of ENTSOE data, modeling and information from national statistics office CBS](https://co2monitor.nl/uitgangspunten).

Now the catch: the website is managed by NetAnders, the same company behind Energieopwek. Their [Terms](https://co2monitor.nl/disclaimer) don't seem to permit automatic scraping without a license.

So not sure how useful it is given the license requirement, but here it is.

**Comment by madsnedergaard** [comment]
cc @pierresegonne, we've talked about this already, right? 🤔

**Comment by pierresegonne** [comment]
Yes I've been in contact with them, and unfortunately, as you've found out, it's the same company behind as energieopwek, who don't want us to use their data for free.

That means that we can't use them as a data source :/

Thanks for sharing this though!
