### ISSUE TITLE
UK live figure does not match 24 hour plot

### ISSUE THREAD

**Issue by samtygier** [electricitymap/electricitymap-contrib#4144]
The UK headline figure has a large difference from the 24 hour plot. Right now the live figure is 262g, but the 24 hour graph suggests it should be around 150g.

![image](https://user-images.githubusercontent.com/1113988/168979035-a5bbcc7d-6d40-414b-958c-aa6012fdafb0.png)

It has been like this for weeks, although it is more obvious sometimes.

I am also using co2signal plugin for homeassistant (https://www.home-assistant.io/integrations/co2signal), which I believe is using the same like UK figure. This have been showing almost identical values every day for the past few weeks. Is the live value actually showing a prediction for a typical day?

![image](https://user-images.githubusercontent.com/1113988/168980248-38a908a3-1484-48ff-9965-42cadab26a06.png)

**Comment by madsnedergaard** [comment]
Hey Sam,
Thanks for opening this issue. I was just answering your email, but let's keep discussion here instead 😄 

Seems like there's two things going on here:

1) the high-value numbers are estimated, but the estimation model seems off - we're looking into it

2) The increase in gas on the last hour is not shown on the graph, but it should be - guess that's a frontend bug somewhere.
<img width="792" alt="Screenshot 2022-05-18 at 09 04 40" src="https://user-images.githubusercontent.com/3296643/168980879-10096edf-c0f9-43e5-a76d-d851a36661d6.png">
<img width="833" alt="Screenshot 2022-05-18 at 09 04 38" src="https://user-images.githubusercontent.com/3296643/168981087-decff2b2-52ac-43ed-b1cc-794ac60f8368.png">

**Comment by samtygier** [comment]
Thanks for looking in to it. (I was not completely sure how closely related electricitymap, co2signal and the HA plug in are, or where the issue is, hence the email and bug report).

**Comment by VIKTORVAV99** [comment]
> The increase in gas on the last hour is not shown on the graph, but it should be - guess that's a frontend bug somewhere.

@madsnedergaard I think this is related to the graphs showing 25 "ticks" (hours) but only generate a bar or account for 24 hours so the last bar is missing.

**Comment by madsnedergaard** [comment]
> > The increase in gas on the last hour is not shown on the graph, but it should be - guess that's a frontend bug somewhere.
> 
> @madsnedergaard I think this is related to the graphs showing 25 "ticks" (hours) but only generate a bar or account for 24 hours so the last bar is missing.

Reminder to self (and @Kongkille): Make sure we fix this while reworking things for historical view :)

**Comment by VIKTORVAV99** [comment]
Fixed by #4353
