### ISSUE TITLE
Parsers `ES_CN.py` and `ES_IB.py` are almost identical

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymap/electricitymap-contrib#4186]
These two parsers are almost identical to each other in structure and they both use the same source.
Is there any reason why these haven't been combined?

I'd be happy to work on it if there is nothing blocking the merger of the parsers.

**Comment by VIKTORVAV99** [comment]
@madsnedergaard I was thinking of starting to work on this as I couldn't find any obvious blockers and was just curious if the backend supported python 3.10 syntax? 

I was particularly interested in using the new pattern matching syntax which is basically a python version of switch case.

**Comment by madsnedergaard** [comment]
Don't think it does, we're running `3.8` on our backend which ingests the parsers and config files, so even if we get it running fine on contrib I'd be wary that it might break something internally.

It's probably worth adding to the backlog, but not sure how much value it would add :)

**Comment by VIKTORVAV99** [comment]
> Don't think it does, we're running `3.8` on our backend which ingests the parsers and config files, so even if we get it running fine on contrib I'd be wary that it might break something internally.
> 
> It's probably worth adding to the backlog, but not sure how much value it would add :)

Functionality wise it won't do much but the match case syntax is a lot cleaner and easier to read IMO.

Example:
```python
match zone_key:
    case DK-DK1:
        # code
    case DK-DK2:
        # code
    case _:
        # default
```

Should be relatively easy to upgrade tho as there is no breaking charges as far as I know.
