### ISSUE TITLE
No data shown in mobile app

### ISSUE THREAD

**Issue by Trolli132** [electricitymap/electricitymap-contrib#4191]
![Screenshot_20220528-112237_electricityMap](https://user-images.githubusercontent.com/87663978/170819388-78fc918e-ae28-4b4d-aa0b-aaf742859146.jpg)

Ich kann schon seit einigen Tagen keine Daten mehr sehen. Fehler besteht auf IPad Pro neustes ios und auf Neustem Android.

![Screenshot_20220528-112616_electricityMap](https://user-images.githubusercontent.com/87663978/170819479-49fa921f-1d27-475d-bfed-1beeddac2b6e.jpg)

**Comment by VIKTORVAV99** [comment]
A few questions to help triage this:
- Does this only apply for Germany or other zones as well?
- Does it apply to the map itself or only the "details" page?
- Have you tried updating the app?
- If updating didn't work or no update was available can you try re-installing the app and see if that work?
<br />
<br />
Note: Please try and stick to English in the future so everyone can easily understand.

**Comment by madsnedergaard** [comment]
Hi @Trolli132, I should have fixed this bug with the latest update (out last week). Can we get you to update (as @VIKTORVAV99 mentions) and try again? :)

**Comment by Trolli132** [comment]
Yeah Update fixed it thank you

Mads Nedergaard ***@***.***> schrieb am Mo., 30. Mai 2022,
08:05:
