### ISSUE TITLE
Possible error in ES->PT exchange

### ISSUE THREAD

**Issue by FelixDQ** [electricitymap/electricitymap-contrib#4225]
There seems to be a discrepancy between [ENTSO-E](https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_CTY&atch=false&dateTime.dateTime=29.05.2022+00:00|UTC|DAY&border.values=CTY|10YPT-REN------W!CTY_CTY|10YPT-REN------W_CTY_CTY|10YES-REE------0&dateTime.timezone=UTC&dateTime.timezone_input=UTC) and [this data source](https://demanda.ree.es/visiona/peninsula/demanda/acumulada/2022-05-29)

I suspect that the ENTSO-E exchange is inverted.
Also looking at Portugal, we see cases where `export > production + import` which shouldn't be possible:
![image](https://user-images.githubusercontent.com/12124251/172605777-2b33aba6-2f82-4402-b404-9ded4b9f84ce.png)

We should reach out to ENTSO-E to understand if this is an error on their side.

**Comment by VIKTORVAV99** [comment]
Unless I am mistaken it looks like it might have been resolved now?

Imports look logical on the map and at first glance ENTSO-E (`ES->FR` + `ES->PT`) and demanda.ree.es (`intercambios int`) seems to be more in line with each other too.

**Comment by FelixDQ** [comment]
Yes, I think you are right! Looking at the last two weeks of data, it seems more reasonable now:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/12124251/175557420-8632af57-d4a1-4d19-98d2-d71bdc49bb46.png">
