### ISSUE TITLE
Drastic differences between GB carbonintensity.org.uk API shown Carbon Intensity and GB electricitymap.org shown intensity

### ISSUE THREAD

**Issue by OwenQWERTY** [electricitymap/electricitymap-contrib#4236]
How can the carbon intensity be so different between the two sources, and would their API not be more accurate. I don't know if you replace working sources/parsers, but it also has a regional breakdown with 14 regions across GB

![Screenshot 2022-06-11 160340](https://user-images.githubusercontent.com/67866804/173193277-565f3ee8-9f89-4e5b-9f1c-06a52bf785f7.jpg)
![Screenshot 2022-06-11 155840](https://user-images.githubusercontent.com/67866804/173193280-9de719aa-385e-43da-bb65-616205cabc7a.jpg)
![Screenshot 2022-06-11 155813](https://user-images.githubusercontent.com/67866804/173193281-1044b4ad-3c78-4cbf-adb0-8bb20b2a40bb.jpg)
![Screenshot 2022-06-11 155744](https://user-images.githubusercontent.com/67866804/173193282-42a4b908-8c01-41e9-b234-4f63b9633bc3.jpg)

**Comment by VIKTORVAV99** [comment]
I think the biggest reason is that the emission factors carbonintensity.org.uk use is vastly different from the ones electricityMap use.

carbonintensity.org.uk:
![Screenshot_20220611-173154_Samsung Notes.jpg](https://user-images.githubusercontent.com/30777521/173194504-099c8919-04a1-411c-ad0c-5fec981972b7.jpg)

ElectricityMap:
![Screenshot_20220611-173504_Brave.jpg](https://user-images.githubusercontent.com/30777521/173194568-1e33f52b-b150-4e67-afee-a2c3fec95dc2.jpg)

(In fact the carbonintensity.org.uk figures more closely match the electricityMap direct emissions.)

This seems to be the biggest factor in the difference co2 intensity for the different platforms although it might not account for 100% of the difference.

**Comment by OwenQWERTY** [comment]
Thank you for your response!

> I think the biggest reason is that the emission factors carbonintensity.org.uk use is vastly different from the ones electricityMap use.

I didn't even consider that they would use such extremely different factors, I think the components of ElectricityMap make more sense and are more balanced overall. However the unknown is assumed to be fossil fuels, and this is not representative for nations actually reducing their carbon consumption.

**Comment by VIKTORVAV99** [comment]
> Thank you for your response!
> 
> > I think the biggest reason is that the emission factors carbonintensity.org.uk use is vastly different from the ones electricityMap use.
> 
> I didn't even consider that they would use such extremely different factors, I think the components of ElectricityMap make more sense and are more balanced overall. However the unknown is assumed to be fossil fuels, and this is not representative for nations actually reducing their carbon consumption.

I used the "standard" figures for electricityMap, unknown production have a region specific emission factor where we have the data. For example for Sweden it is 238 as it is 98% biomass. It does however look like we don't have one for GB yet so you are welcome to open a new issue for that. :)
