### ISSUE TITLE
relative capacity usage of power sources missing

### ISSUE THREAD

**Issue by DerDakon** [electricitymap/electricitymap-contrib#4255]
I remember there as been a "using nn% of the installed capacity xx GW/yy GW" for power sources. This seems to have got lost somewhere, at least I don't see it in the German tooltips anymore.

It _is_ there for interchanges, e.g. NL -> DE. It could be hidden there for some of the entries when the actual capacity is unknown as the number is pretty pointless then.

**Comment by VIKTORVAV99** [comment]
Thanks for reporting this!

I'm closing this issue as the code was fixed in #4238 and it will be fixed on the website as soon as the electricityMap team pushes a new release.
