### ISSUE TITLE
US EIA Parser is down

### ISSUE THREAD

**Issue by FelixDQ** [electricitymap/electricitymap-contrib#4270]
Example Error from logs:
```sh
EIA error, for series_id [EBA.FMPP-ALL.NG.WND.H]: invalid series_id. For key registration, documentation, and examples see https://www.eia.gov/developer/

{'location': 'EIA.py:_fetch_series'}   
```

EIA is set to deprecate its V1 API in November 2022
> EIA will discontinue support for its [legacy API (APIv1)](https://www.eia.gov/opendata/v1/) in November, 2022. Excel add-in v1 sheets will continue to function as they are. Please refer to our [documentation](https://www.eia.gov/opendata/documentation.php) for the APIv2 interaction methods

It seems like EIA broke something in their V1 API. If the API doesn't come back up soon, we should consider upgrading our parser to their V2 API.

**Comment by systemcatch** [comment]
Hey @FelixDQ I haven't looked at the changes yet. Possibly it won't be too hard to adapt the old framework to the new.

If it involves a full rewrite I might struggle to find the time to do it properly.

**Comment by FelixDQ** [comment]
Alright, thank you, Chris. We'll take a look and decide from there :-)

**Comment by FelixDQ** [comment]
Looks like the parser is up again now, however it is a bit delayed. They issued a press release explaining that they had a system issue and that the data will be delayed. https://www.eia.gov/pressroom/releases/press504.php

I'll close this issue for now as I expect it to work fine again soon. I'll create a new issue for upgrading to the V2 API so that we remember to upgrade before November.
