### ISSUE TITLE
Estimated data for Estonia includes impossible level of generation from oil

### ISSUE THREAD

**Issue by autipial** [electricitymap/electricitymap-contrib#4294]
The estimated generation for Estonia includes 922 MW of generation from oil today, while the installed capacity is only 52 MW.

**Comment by VIKTORVAV99** [comment]
Just going to add some complimentary information but it does look like the estimation model is way out of what is reasonable with it producing data that is utilizing 1770% or so of the installed production. (Presumably cause the data from ENTSO-E is currently unavailable)

It's however a little curious that it decided to add almost 1 GW of production for no apparent reason? Maybe you could give us a hint as to why @pierresegonne?

SCREENSHOTS:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/30777521/175835169-ff25631d-5f90-4836-a481-453fd7a1252f.png">
<img width="343" alt="image" src="https://user-images.githubusercontent.com/30777521/175835183-8a2495e6-cc4b-40e9-b35a-4522f45d45d3.png">

**Comment by pierresegonne** [comment]
Thanks for raising this, it's indeed suspicious. I'll look into it in the coming days

**Comment by VIKTORVAV99** [comment]
@pierresegonne I haven't seen this issue the past few days. Is it estimation model "fixed" now so we can close this issue?
