### ISSUE TITLE
New data feed for GB-NIR

### ISSUE THREAD

**Issue by Andy747** [electricitymap/electricitymap-contrib#4302]
Since the soni.ltd.uk API's are broken, there is another data source that might be possible to use: [https://www.smartgriddashboard.com/#ni](https://www.smartgriddashboard.com/#ni)

I could not find an official API to directly pull the data from. However, perhaps the data can be pulled from the site?

If anyone can help to get GB-NIR working again, I would be very grateful.
Thanks.

**Comment by madsnedergaard** [comment]
Hi, thanks for opening this. There's already been discussions around this in #2339 and #2916, so I'll close this as duplicate :)
