### ISSUE TITLE
New interconnection between Slovenia and Hungary

### ISSUE THREAD

**Issue by seba1337** [electricitymap/electricitymap-contrib#4316]
There's a new interconnection between Slovenia and Hungary (news: https://www.eles.si/obratovanje/novice-za-poslovne-uporabnike/ArticleID/19330/Vklop-%C4%8Dezmejne-povezave-Cirkovce-H%C3%A9v%C3%ADz-na-meji-med-Slovenijo-in-Mad%C5%BEarsko-v-obratovanje).

It is also available on ENTSO-E: https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=02.07.2022+00:00|CET|DAY&border.values=CTY|10YSI-ELES-----O!BZN_BZN|10YSI-ELES-----O_BZN_BZN|10YHU-MAVIR----U&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

Re, S

**Comment by VIKTORVAV99** [comment]
Thanks for opening this issue. 

The exchange has already been added to the code base and we just need a new release for it to show up on the map.
