### ISSUE TITLE
Missing data for Switzerland

### ISSUE THREAD

**Issue by autipial** [electricitymap/electricitymap-contrib#4322]
I noticed on today's data for Switzerland that some of the data is missing during one hour. Instead, a white rectangle is displayed. Hovering over with the cursor doesn't show anything.
See screenshot below:

![bug_CH](https://user-images.githubusercontent.com/7460404/177048740-6d1549e4-88d7-4a63-aaff-f94df673aa4d.png)

**Comment by jarek** [comment]
The estimates today were also quite choppy, with hydro production expected by the estimation model being much lower than actual. Screenshot is from today, with times in timezone UTC-4

![ch](https://user-images.githubusercontent.com/47415/177065463-7443aaba-46d7-4a36-a40b-8c218fe464a6.png)

**Comment by VIKTORVAV99** [comment]
@pierresegonne estimation models seem to be your thing, any idea of what is going on here. Is it similar to what happened with Estonia?

**Comment by pierresegonne** [comment]
Hey, sorry I was on holidays. From what I've heard from the team there was an incident on our side that meant that our estimates were not propagated to the live map. Should have been fixed now, let me know if you see something suspicious.
I'll close the issue for now, we'll reopen it if it happens again.

**Comment by pierresegonne** [comment]
@Kongkille  FYI for the UI issue - I'll let you decide whether we should create an issue for that

**Comment by autipial** [comment]
Hey, I think there is a similar behavior today with the data of Switzerland.

![2022 07 20 CH](https://user-images.githubusercontent.com/7460404/179955152-8a5de3fc-9959-4cf9-b81f-67098855240d.png)

I suspect it is also happening with the data of Austria -- not fully sure, though. But trying to hover over the white rectangle gives the impression that it might be the same issue.

![2022 07 20 AT](https://user-images.githubusercontent.com/7460404/179955583-ab292e9d-2c83-4e89-a8df-ca3ba0c29bec.png)
