### ISSUE TITLE
Map CO2 intensity colourmap does not change with values

### ISSUE THREAD

**Issue by mueslo** [electricitymap/electricitymap-contrib#4349]
When you e.g. move the time of day slider, the values display when hovering over different countries change, but the colours themselves do NOT change to reflect those new values.

**Comment by VIKTORVAV99** [comment]
The new time slider is part of a new feature that has not fully released yet so not everything works just yet.

However if you go to https://staging.electricitymaps.com you can get a more complete view on how it's supposed to work. (switch to 30 days, 12 months or 5 years).

The new feature should launch any day now though so the wait won't be long.
