### ISSUE TITLE
Doesn't show % of total in the production mode tooltip because the total production and imports are missing

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymap/electricitymap-contrib#4357]
Looks like the recent historical view update introduced a small bug.

On the production mode tooltip you can no longer see the share of electricity that comes from said mode (in %).
Screenshot as an example:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/30777521/180154990-d941ff91-1dd0-45d4-98bd-4833e452b81f.png">

**Comment by VIKTORVAV99** [comment]
CC @Kongkille, looks like we got out first "historical view" bug, I haven't had time to dig into it yet but hopefully it's a quick fix.

**Comment by Kongkille** [comment]
Yes i am on this right now. The issue seems to be my process of simplifying in the backend, where we are losing one value completely which makes this into a nan value. 

Instead of fixing this in the frontend, I'll fix it in the backend so we do not have to deploy a new version.

**Comment by VIKTORVAV99** [comment]
> Yes i am on this right now. The issue seems to be my process of simplifying in the backend, where we are losing one value completely which makes this into a nan value. 
> 
> Instead of fixing this in the frontend, I'll fix it in the backend so we do not have to deploy a new version.

Sound great! 🎉

**Comment by Kongkille** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/45588799/180233122-5f7d552f-c667-4f8a-8dfd-5b0f4ce47fec.png">

Looks like it's working again!
