### ISSUE TITLE
Setting buttons are too close to the top bar on mobile

### ISSUE THREAD

**Issue by Kongkille** [electricitymap/electricitymap-contrib#4366]
**Describe the bug**
The setting and info buttons on Mobile are too high, so on some devices it can become impossible to click on.

**To Reproduce**
1. Go to Map on mobile device
2. See that there is almost no spacing on top of the settings and info buttons

**Expected behavior**
There should be more space on top of the buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/45588799/180774030-34256d86-000a-45cc-a730-0f95d50cd2cc.png)

**Smartphone (please complete the following information):**
 - Device: Iphone SE
 - Version: 1.3.4

**Comment by ovbm** [comment]
Hey, In the app the added padding is not sufficent to fix the issue (see img), as the viewport spans the entire width and height of the device. You could probably solved this by wrapping the top buttons in a safe-area-inset container and add more padding to the bottom drawer when in the app.

![IMG_3954](https://user-images.githubusercontent.com/20746301/181457771-6a8ef996-e3ec-48d2-884d-9b4aa49e4b8f.jpeg)

**Comment by Kongkille** [comment]
Hey @ovbm!

Yes it seems our safe-area-inset styling disappeared either with an update to Cordova or when we shuffled the UI around. 

I am implementing it now and testing on the newer ios devices and android. Hopefully a new version is live early next week
