### ISSUE TITLE
Confusing output with 5 year historical view at El Hierro (Spain)

### ISSUE THREAD

**Issue by AndBerna** [electricitymap/electricitymap-contrib#4387]
@Kongkille minor issue on the historical view. Apart from that, great feature! 😍

**Describe the bug**
 When looking to the historical  ( 5 years) at el Hierro the results are confusing:
- No results provided ( despite there is at least, one year of data as it can be seen in the 12 months view)
- Empty production chart 
- Source outputs: ? 

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to 'El Hierro (Spain)'
2. Click on '5 Years' 
3. Scroll down to 'Electricity production in the last 5 years'

**Expected behaviour**
- Yearly graph from the available years
- Carbon intensity from the available years
- No graph if there is no data displayed
-  Same source as 24h/30days/12 months ( if there is data displayed)

**Screenshots**
<img width="448" alt="Screenshot 2022-07-27 at 16 33 41" src="https://user-images.githubusercontent.com/45770697/181275134-adc0e99d-4398-435c-be44-ac5a12c0dcc0.png">

**Desktop:**
 - OS: MacOS
 - Browser: Chrome

**Comment by strassburger** [comment]
New Info.
first date of data for El Hiero in "demanda.ree.es" is 2012-02-29
works:
https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas/2012-02-29/2
does nor work:
https://demanda.ree.es/visiona/canarias/el_hierro5m/tablas/2012-02-28/2
Hope helps

**Comment by Kongkille** [comment]
Yes so the reason this is happening is the way we are handlings time windows. Right now we will only show data if there's a value for all expected hours. I.e for 24 hours, we expect all 24 hours.

I've created a new issue to keep track of this
