### ISSUE TITLE
Allow missing entries in time window

### ISSUE THREAD

**Issue by Kongkille** [electricitymap/electricitymap-contrib#4398]
## Description

Cause of #4387. 

The app-backend currently either returns nothing or all expected values. For example for 24 hours, if one hour is missing data completely we will not return any values.

This was implemented to ensure we do not become out of sync with history and state (#3949) and also to minimize the file sizes.

I.e if the length of the array is 24 and the other is 25 but the index is shared, the state and history will become out of sync.

## Solution

The main cause of complexity here is that we use an index to keep track of time. We use 'selectedZoneTimeIndex' which is an index that can both be used in history and state.

I think the optimal solution would be to deprecate 'selectedZoneTimeIndex' and instead simply have a 'selectedDatetime' and change the data structure to map from datetime to zoneData instead of using an index to map to zoneData.

I believe this is more intuitive to work with and guarantees that we do not become out of sync.

Alternative solution:

A potentially less demanding solution would just be to fill in missing values in the array. I.e. we always ensure that there is 24 entries for 24 hours and 5 values for 5 years.

**Comment by VIKTORVAV99** [comment]
It might be worth it to just fill the array in the meantime to clear up some of these issues.

Just a small nitpick, 24 hours are 25 entries as we show for example 09:00 to 09:00 the next day aka 24+1 hour.

**Comment by Kongkille** [comment]
> It might be worth it to just fill the array in the meantime to clear up some of these issues.
> 
> Just a small nitpick, 24 hours are 25 entries as we show for example 09:00 to 09:00 the next day aka 24+1 hour.

That is true, updated the issue
