### ISSUE TITLE
Why is Taiwan a country, Taiwan is a part of China, please amend it as soon as possible

### ISSUE THREAD

**Issue by aza12138** [electricitymap/electricitymap-contrib#4409]
![Snipaste_2022-08-03_16-04-17](https://user-images.githubusercontent.com/60005614/182557078-8088d22c-3287-40ab-9c6b-422e597cd292.jpg)

**Comment by Kongkille** [comment]
Hi @aza12138, seeing that this is not part of the open-source code but a text on our academic website, I am closing this issue because there is no direct actions to be taken from the community.
