### ISSUE TITLE
Ideas for some country that are dived.

### ISSUE THREAD

**Issue by livioavalle** [electricitymap/electricitymap-contrib#4419]
I live in Italy, but on electricity map the country is divided in 4 continental region and two islands. Would be possible to have a switch that merge the value of the 4 region or also the entire country? So that everyone can have the detailed data for different region or a single data for the entire country to compare with other country that are not dived. Thanks

**Comment by Kongkille** [comment]
Hi @livioavalle, this is actually a feature that we intend to work on very soon for the exact reasons you're mentioning here. We'll create a new issue for this soon, so stay tuned! :)

I'm closing this specific issue in favour of having a singular thread on #3309
