### ISSUE TITLE
Faroe Islands, additional wind installed.

### ISSUE THREAD

**Issue by Bjarkigd** [electricitymap/electricitymap-contrib#4421]
25.2 MW of windpower has recently been installed and gone live in the Faroes, making it a total of 43.5 MW of wind installed in the Faroes now https://www.effo.fo/effo/umeffo/gron-orka/
The live data is at https://www.sev.fo/framleidsla/el-orka-i-foroyum/ (the icon for the windfarm hasn't been added in the map, but the production is there) 
An additional wind farm is under construction atm, to be added later in the year.

Edit: the installed solar capacity is 0.24 MW https://www.sev.fo/um-okkum/elskipanin/orkuverk/

**Comment by VIKTORVAV99** [comment]
I'll create a PR with the updated capacities tomorrow. The parser should already pick up the additional wind protection but I'll take a look to be sure as well.

**Comment by VIKTORVAV99** [comment]
@Bjarkigd before I create this PR could you confirm the installed capacity for oil is 99.7 MW?

**Comment by Bjarkigd** [comment]
99.7MW is correct

**Comment by VIKTORVAV99** [comment]
Great, I'll create a PR for it right away.
