### ISSUE TITLE
Time slider appears above loading screen

### ISSUE THREAD

**Issue by corradio** [electricitymap/electricitymap-contrib#4426]
**Describe the bug**
The time slider component appears above the loading screen.

**To Reproduce**
1. Open the app

**Expected behavior**
It should appear under

**Screenshots**
![image](https://user-images.githubusercontent.com/1655848/183296364-1cb42d0b-e9b9-4015-a109-efae58601564.png)

**Smartphone (if relevant):**
 - iOS latest app version.

**Comment by waltonzt** [comment]
@corradio I can take a shot at fixing this if you would like.

**Comment by corradio** [comment]
> @corradio I can take a shot at fixing this if you would like.

That would be amazing! cc @Kongkille @rasmusjeppsen
