### ISSUE TITLE
Dynamic loading screen

### ISSUE THREAD

**Issue by corradio** [electricitymap/electricitymap-contrib#4429]
**Is your feature request related to a problem? Please describe.**
The loading screen seen when the app is opened is currently static. I've seen users wonder what is happening.
An indication that this is a loading indicator would be nice

**Describe the solution you'd like**
We could simply have it blink? Many creative directions can be investigated, but having something quick and dirty would already help!

**Comment by VIKTORVAV99** [comment]
Making it blink would probably be a good immediate fix but I and @Kongkille have talked a little about making the dots in the new logo a loading "spinner" (does not need to actually spin) in #4330 but I don't think either of us has had to look into that yet.

We would do this by animating the SVG itself, that way it will scale perfectly just as it currently does and it will keep the file size down.

**Comment by waltonzt** [comment]
@VIKTORVAV99 @corradio Hey there, my name is Zack and I wanted to take a shot at contributing to the project. I created a pull request that animates the SVG logo and hooked it up where I saw fit. Please let me know what you think!

**Comment by corradio** [comment]
Amazing! Someone from the Electricity Maps team will review soon :)

**Comment by VIKTORVAV99** [comment]
I left a few comments on the PR but it looks good so far!
