### ISSUE TITLE
Co2 Forecast for personal use

### ISSUE THREAD

**Issue by the-red-lily** [electricitymap/electricitymap-contrib#4473]
**Is your feature request related to a problem? Please describe.**
I'd like to use electricitymap to plan my appliance usage, i.e. oven, laundry, EV charging, etc. However I can only see data for earlier in the day (or maybe real-time) and have no way of knowing if Co2 intensity will decrease later in the day.

**Describe the solution you'd like**
The ideal solution would be a daily notification system. The alert might look something like:
"Predicted lowest Co2 intensity at 12pm: 100gCO2eq/kWh"

**Describe alternatives you've considered**
The information could be provided as a new API, or alongside the existing https://www.co2signal.com/ API. Then I could implement the notifications using an external service

**Additional context**
More information added to the non-commercial forecast API would also be great. But I understand the need to separate personal use from commercial use, so the API could be designed to support only this use case with minimal data leakage

**Comment by corradio** [comment]
Have you looked at https://ifttt.com/electricitymap ?

**Comment by the-red-lily** [comment]
The current API seems to me to only have real-time data, rather than a
prediction of the future.

The only info I'd have is realtime co2 impact. I wouldn't know if it will
be lower or higher in an hour from now (and knowing the answer might change
energy use habits)

I ask about predictions because I see it suggested that the pro version
offers predictions. I'm not sure which areas offer predictions or how those
predictions line up with reality though

**Comment by Kongkille** [comment]
@the-red-lily at this time, we are not providing forecasts for free as this is part of our commercial offerings.

I completely understand your use-case and perhaps we can release it as part of co2signal in the future but not at this time unfortunately.
