### ISSUE TITLE
Batterycapacity in at least Germany

### ISSUE THREAD

**Issue by Lumpf** [electricitymap/electricitymap-contrib#4481]
Hello, 
i recognized, that in Germany the battery capacity has grown from 750 MW to 2,5 GW. On the other hand there is no movement  pn this scope. Does this 2,5 GW mean central storage or is it the collected power of all private in-home batteries. 
Thanks for a small replay. 

KR Lumpf

**Comment by jarek** [comment]
Hello,

The 2.5 GW German battery capacity comes from Fraunhofer ISE https://energy-charts.info/charts/installed_power/chart.htm?l=en&c=DE&stacking=single&chartColumnSorting=default&legendItems=1111111111111 and was added in https://github.com/electricitymap/electricitymap-contrib/pull/4411

It seems rather high to me based on a cursory reading of https://de.wikipedia.org/wiki/Liste_von_Batterie-Speicherkraftwerken#Deutschland but I guess Fraunhofer has a better reckoning than I do...

**Comment by VIKTORVAV99** [comment]
Is it possible they also include compressed air storage in the battery category?

I know Germany has some compressed air storage (that should still be operational) but it doesn't seem to be accounted for in a individual category.

**Comment by Lumpf** [comment]
Well, I’m wondering why there is the rapid increase by 300%. From what I know the flywheels and compressed air are in a proving state and small sized. Maybe the big amount of small storages makes it so difficult to monitor. I’m hoping for big size batteries. Hopefully Natrium ion based. W‘ll see. Nevertheless thanks for the nice monitoring tool. One of my favourites.👍

KR Lumpf 

Von meinem iPhone gesendet

**Comment by jarek** [comment]
I guess Fraunhofer ISE would be the best place to ask about the rapid increase: https://energy-charts.info/contact.html?l=en&c=DE

**Comment by Lumpf** [comment]
I‘ll ask Mr. Burger. Thanks for the link. If I get feedback, I’ll try to translate and will forward this to you. Thanks so far.


KR Lumpf

Von meinem iPhone gesendet

**Comment by Lumpf** [comment]
Hello,

today, i got feedback from Prof. Dr. Burger, who initiated the Energy-Charts. 
This is the situation: 
Until last week, Energy-charts used Data from the „Bundes Netz Agentur“ which is the federal department responsible for power, fuels and digital networks. 
The data were from 31.05.22 and outdated.
Since the last week, Energy-Charts use data from the „Markt Stamdaten Register", which is a central register of all Windturbines, PV generators, and batterystorages. 
In this register all batteries were listet, even the smallest (like mine 3,5kWh Akku) in private homes. 
So they work and have a damping effect on the up and downs off the power. 
Sadly only batteries with a capacity  > 100kWh have to give a feedback every quarter of an hour. 
So the amount has grown, but since the batteries were to small they have no effect on your app.
hopefully, this changes soon. 

I add the original conversation in German below. 

Thanks for responding and your outstanding work. 

KR Olaf Lanfermann



My question: 
Hallo Herr Burger,

Erst einmal ein Kompliment für die Bereitstellung der Daten zur Stromerzeugung auf Ihrer Seite Energy-Charts.
Die Webseite electicitymap greift wohl auf Ihre Daten zu.
Mir ist auf deren Site aufgefallen, das Batteriespeicher mit aufgeführt werden. 
Finde ich in der aktuellen Lage sehr interessant.
Bis vor kurzem (letzte Woche?) wurden hier 750 MWh an Kapazität geführt.
Seit einer Woche stehen da nun 2,5 GWh. 
Auf Rückfrage bekam ich Ihre Mail, da die die Daten auch nur von Ihnen abfragen

Leider sieht man dort noch keine Bewegungen. 

Fragen: 
Sind das Großspeicher oder kommutierte Hausspeicher
Wann / Wird man Speicherstände mit in die Grafiken einbinden können?
Gibt es vielleicht Quellen, die man direkt anzapfen kann um sich aktuell ein Bild zu machen?
ich bin rein privat unterwegs, aber ein Jäger und Sammler für diese Daten.
Öffentliche  Statistiken sind zum Teil Jahre alt.

Vielleicht haben Sie ja mal einen Link.

Mit freundlichem Gruß 


Olaf Lanfermann


The answer: 
Hallo Herr Lanfermann,

bei den Batteriespeichern hatten wir zuerst die Daten der Bundesnetzagentur gezeigt. Gemäß der Kraftwerksliste haben sie eine Leistung von 597 MW, Stand: 31.05.2022. Evtl. werden hier nur die Speicher berücksichtigt, die am Strommarkt teilnehmen.
Jetzt machen wir eine eigene Auswertung mit den Daten des Marktstammdatenregisters. Damit kommen wir auf eine installierte Leistung von 2,5 GW und eine Speicherkapazität von 3,96 GWh.
Im Marktstammdatenregister müssen alle Batteriespeicher angemeldet werden, unabhängig von der Größe.  
Alle Kraftwerke und Speicher, die am öffentlichen Netz arbeiten, müssen ab einer installierten Nettoleistung von 100 MW die Viertelstundenwerte ihrer Erzeugung melden. Das gilt wahrscheinlich auch für Batteriespeicher. Bisher gibt es aber keine Daten. Wahrscheinlich sind alle Speicher kleiner als 100 MW. Sobald ein Speicher größer 100 MW am Netz ist, sollten auch Viertelstundenwerte zur Verfügung stehen.

Viele Grüße

Bruno Burger
---
Prof. Dr. Bruno Burger
Senior Scientist
Division Power Electronics, Grids and Systems
Fraunhofer Institute for Solar Energy Systems ISE

**Comment by VIKTORVAV99** [comment]
Great, sadly this is only part of the problem with battery storage in Europe, most countries like Germany use the ENTSO-E data from the transparency platform but it currently does not contain any battery information.

We should probably contact ENTSO-E about that and see what the status of said data is.
Since the prevalence of grid connected big battery systems is only increasing this will be more and more important in the future.

**Comment by VIKTORVAV99** [comment]
@Lumpf would you consider this issue closed or do you want to keep it open a while longer?

I personally don't think there is much we can do about it and technically the data is more accurate now.

**Comment by Lumpf** [comment]
Thanks for asking. Feel free to close the case. Sorry I didn’t know that I had to close it from my side. 

Thanks 🙏 

Von meinem iPhone gesendet

**Comment by VIKTORVAV99** [comment]
No worries! You didn't have to do anything I just wanted to make sure we where all on the same page before closing it.

**Comment by Lumpf** [comment]
Did you recognise?



Von meinem iPhone gesendet
