### ISSUE TITLE
Direct linking to a region gives error

### ISSUE THREAD

**Issue by gregbarton** [electricitymap/electricitymap-contrib#4482]
**Describe the bug**
Direct linking to a region (like https://app.electricitymaps.com/zone/FO) renders the following error:

Error message: undefined is not an object (evaluating 'g[b].geography')

**To Reproduce**
1. Paste https://app.electricitymaps.com/zone/FO in URL bar.
2. See error

**Expected behavior**
Render region.

**Screenshots**
![image](https://user-images.githubusercontent.com/1505300/186076231-5c1f6c6c-c97e-4cf4-a40d-8edb51639692.png)

**Desktop (if relevant):**
 - OS: MacOS
 - Browser: chrome
 - Version 104.0.5112.101

**Comment by VIKTORVAV99** [comment]
I think this one might be easily explained actually and that is that the `FO` zone don't exist anymore.
It was recently split up into `FO-SI` and `FO-MI` to get higher "resolution" in the data.
Looks like the full deployment has not happened yet though so the frontend and backend might be out of sync so I would still consider this a bug.

Have you tried it with any other zones?

**Comment by Kongkille** [comment]
Thanks for submitting this @gregbarton 

This is indeed a current bug in the app, we actually already have an issue open on this one #4172 so I'll just close this one in favor of the existing issue
