### ISSUE TITLE
Exchange arrow between `FR-COR` and `IT-SAR` is inverted

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymap/electricitymap-contrib#4483]
**Describe the bug**
The `FR-COR->IT-SAR` exchange arrow is inverted. Oops...

**To Reproduce**
1. Click on `FR-COR` or `IT-SAR`
2. Compare the flow with the exchange arrow direction.

**Expected behavior**
That the arrow is pointed the other way.

**Screenshots**
![image](https://user-images.githubusercontent.com/30777521/186088336-51b7dc33-76c1-44dd-b43e-187900239e13.png)

**Comment by Teniola-theDev** [comment]
I would love to be assigned to this issue.

I ran it and checked the possible solution via the developer console and it worked.

Thank you for pointing it out.

**Comment by VIKTORVAV99** [comment]
> I would love to be assigned to this issue.
> 
> I ran it and checked the possible solution via the developer console and it worked.
> 
> Thank you for pointing it out.

I'd be happy to assign you, let me know if you have any questions!

**Comment by Teniola-theDev** [comment]
I'm sorry, the method I planned to use is a bit unsustainable. I don't mind getting unassigned but I really hope to get back here when I have leveled up my skills and hopefully work around with other issues.

**Comment by VIKTORVAV99** [comment]
Okay, If you want I could give you some hints?
The issue is pretty straightforward once you get more familiar with the codebase.

But don't feel obligated in any way, if you want to be unassigned that is no problem and I'll take care of this myself. 🙂

**Comment by Teniola-theDev** [comment]
Yes, I would love hints! Thank you for being so kind.

**Comment by VIKTORVAV99** [comment]
Nice!
Okay so some project structure first then we can easily spot the issue.
While the frontend code is normally stored in `/web` the exchanges (among others) are a little special as they have their values stored in `/config/exchanges.json` instead.

Now here we can see that an exchange is made up of an object that consists of:
- `lonlat` - Longitude and Latitude of the exchange
- `parsers` - The parsers used to fetch data.
- `capacity` - The exchange capacity of the exchange (this is optional and can be omitted if there is no good capacity source.)
- `rotation` - This is the important one in our case, it is a ° values that controls the rotation. 0 is up and 180 is down for example.

That should be everything you need for this issue, but let me know if you have any questions!

**Comment by Teniola-theDev** [comment]
Yes! Thank you. I found it and I will be sending a pull request soon. Thank you!
