### ISSUE TITLE
Date not available in the "Origin of Electricity in the last 24 hours" chart pop-up

### ISSUE THREAD

**Issue by AndBerna** [electricitymap/electricitymap-contrib#4511]
**Describe the bug**

Date available on the pointer pop-up of `Carbon intensity` chart but not on the `Origin of electricity in the last 24 hours`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Electricity Maps app`
2. Click on `any country`
3. Scroll down to `Electricity Consumption`
4. Place the pointer on top of the graph
5. Scroll down to `Origin of Electricity in the last 24 hours`
6. Place the pointer on top of the graph

**Expected behaviour**
Date information on the pop-up of all the graphs. I would help to clarify where is the pointer on the X axis. 

**Screenshots**
Date available in the `Electricity consumption pop-up`
<img width="352" alt="Screenshot 2022-08-29 at 15 28 32" src="https://user-images.githubusercontent.com/45770697/187213034-db017999-423a-44da-ab67-e4c5d3f0e789.png">
But not on the `Origin of Electricity in the last 24 hours `

<img width="440" alt="Screenshot 2022-08-29 at 15 29 30" src="https://user-images.githubusercontent.com/45770697/187213262-1b1e773f-356f-4a14-8b19-875f14ae255e.png">

OS: macOS
Browser: Chrome

**Comment by VIKTORVAV99** [comment]
This should be fixed by #4506.
