### ISSUE TITLE
Old links broken - https://www.electricitymap.org/?page=map no longer leads to the map

### ISSUE THREAD

**Issue by q--** [electricitymap/electricitymap-contrib#4515]
I have an old bookmark for https://electricitymap.org/?page=map&solar=false&remote=true&wind=true. There are web pages with [similar links](https://www.google.com/search?q=https%253A%252F%252Fwww.electricitymap.org%252F%253Fpage%253Dmap%2526solar%253Dfalse%2526remote%253Dtrue%2526wind%253Dfalse).

However, https://www.electricitymap.org/?page=map no longer leads to the map but to the homepage. `page=map` URLs should take you directly to the map.

**Comment by corradio** [comment]
Hi @q--,
Can you try now? I added a page rule on cloudflare:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/1655848/187404364-364caafa-9cd7-4049-b7b6-15076e4d9723.png">

It seems to work with:
- https://www.electricitymap.org/?page=map
- https://electricitymap.org/?page=map

cc @tonypls @Kongkille

**Comment by q--** [comment]
It works, but note that as a query parameter may appear anywhere in the query string there could still be some broken links out there. E.g. https://electricitymap.org/?x&solar=false&remote=true&wind=true&page=map& does not work

**Comment by corradio** [comment]
Correct, however in practice this should never happen as the system which built the query strings always puts page first.
It should do the trick for now! Feel free to re-open if that doesn't solve it.
