### ISSUE TITLE
Cant Open the App

### ISSUE THREAD

**Issue by Trolli132** [electricitymap/electricitymap-contrib#4519]
![Screenshot_20220901-124028_Electricity Maps](https://user-images.githubusercontent.com/87663978/187895608-5535a148-cfe5-4718-a3d5-461fc14b6a8b.jpg)

App is not working S21Fe
Android Version 12 
One Ui 4.1
App Version 1.3.6

**Comment by STSGC** [comment]
Same here

**Comment by jdesboeufs** [comment]
Same here.
iPhone 12 Mini - last iOS

**Comment by VIKTORVAV99** [comment]
This seems to be the same issue as #4521.

**Comment by joandotcodina** [comment]
Same here S21

**Comment by VIKTORVAV99** [comment]
Hi @jdesboeufs, @STSGC, @joandotcodina, @Trolli132 could you check if it's working now?

It's working for me locally so if it's working for you guys as well I'll go ahead and close these issues.

**Comment by joandotcodina** [comment]
Yes, now its working.

Ty!

El dc., 7 de set. 2022, 7:58, Viktor Andersson ***@***.***>
va escriure:

**Comment by jdesboeufs** [comment]
It's working here too! ✌️

**Comment by VIKTORVAV99** [comment]
Closing this as it seem to have been resolved!
