### ISSUE TITLE
Error upon loading

### ISSUE THREAD

**Issue by kmarekspartz** [electricitymap/electricitymap-contrib#4521]
**Describe the bug**
When loading the application on iOS I get an error message. 

**To Reproduce**
1. On iOS
2. Open the app

**Expected behavior**
The app would load

**Screenshots**

> Oh no, something went wrong...
> Please let us know [on Github](https://github.com/electricitymap/electricitymap-contrib) so we can fix this!
> `Error message: undefined is not an object (evaluating '[t,e]')
Url: file:///private/var/containers/Bundle/Application/52513B42-C8F8-4173-A721-6A0A8332AC37/Electricity%20Maps.app/www/electricitymap/index_en.html#/map`

![F012462E-3F25-4A12-8090-EB907C7A5C61](https://user-images.githubusercontent.com/969868/187909185-eb3ec985-86a7-4652-9aaa-6d9c599c9a7d.png)

**Smartphone (if relevant):**
 - Device: iPhone 12 Mini
 - OS: iOS 15.6.1

**Additional context**
It worked fine a few days ago

**Comment by VIKTORVAV99** [comment]
I get a similar error (but not identical).

> Error message: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
Url: file:///android_asset/www/electricitymap/index_sv.html#/map

OS: Android 12
App version: 1.3.6

**Comment by PascalDk** [comment]
Same issue here.

_Error message: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
Url: file:///android_asset/www/electricitymap/index_en.html#/map_

**Comment by Kongkille** [comment]
Hi all, sorry about this. We are working on it! Android should be up very soon, iOS is pending a new version approval

**Comment by otmezger** [comment]
Same issue here:

`Error message: undefined is not an object (evaluating '[t,e]')
Url: file:///private/var/containers/Bundle/Application/A8083EC8-068A-4990-A2A6-3C5BE9B51D04/Electricity%20Maps.app/www/electricitymap/index_en.html#/map `

**Comment by MarcusNHofer** [comment]
Same issue since days...

**Comment by VIKTORVAV99** [comment]
> Same issue since days...

The team is aware of the issue and working on it but unfortunately it happened just before the weekend. Hopefully we'll get a fix soon.

**Comment by VIKTORVAV99** [comment]
Hey @kmarekspartz, @otmezger, @PascalDk could you guys try and see if it's working for you now?

It's working for me personally.

**Comment by otmezger** [comment]
It’s working now. Thanks.

**Comment by kmarekspartz** [comment]
Same! I think we're good to close.

**Comment by VIKTORVAV99** [comment]
Closing this as it seem to have been resolved!
