### ISSUE TITLE
Error on opening app, Android

### ISSUE THREAD

**Issue by jparta** [electricitymap/electricitymap-contrib#4524]
**Describe the bug**
The following error is shown on opening the application:

`Error message: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
Url: file:///android_asset/www/electricitymap/index_en.html#/map`

Pressing "back to map" produces the following popup:
`net::ERR_FILE_NOT_FOUND
(file:///map)`

**To Reproduce**
1. Open app
2. See error

**Expected behavior**
App opens normally

**Screenshots**
![Screenshot_2022-09-01-15-17-10-88_4fe31c2c1d15886b5de3320b8ecf29e9.jpg](https://user-images.githubusercontent.com/25590558/187914076-3ed38676-dfcd-4696-b6c4-b466af5abc3a.jpg)
![Screenshot_2022-09-01-15-29-37-16_4fe31c2c1d15886b5de3320b8ecf29e9.jpg](https://user-images.githubusercontent.com/25590558/187914109-ab7c6c5d-1134-4a5d-9633-d0a7a35ca792.jpg)

**Smartphone:**
 - Device: Oppo Reno2 Z
 - OS: Android 11 / ColorOS V11.1

**Comment by VIKTORVAV99** [comment]
This seems to be the same issue as #4521.

**Comment by jparta** [comment]
> This seems to be the same issue as #4521. 

Should I close this?

**Comment by VIKTORVAV99** [comment]
> > This seems to be the same issue as #4521.
> 
> Should I close this?

I'll leave that up to you, either works as we will close all of these together if they are still open.

**Comment by VIKTORVAV99** [comment]
Closing this as it seem to have been resolved!
