### ISSUE TITLE
App bug at startup

### ISSUE THREAD

**Issue by REEFH** [electricitymap/electricitymap-contrib#4537]
**Describe the bug**

Error message: undefined is not an object (evaluating '[t,e]')
Url: file:///private/var/containers/Bundle/Application/53ECF9A2-B1E8-42FD-82A7-37ECE9D1F1AB/Electricity%20Maps.app/www/electricitymap/index_en.html#/map

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/42771705/188478068-85f2b673-eb5a-4ae4-9a88-9e6f23591499.png)

**Desktop (if relevant):**
 - OS: iOS
 - native App
 - because of this error a version number can't be acquired

**Smartphone (if relevant):**
 - Device: iPhone 13 mini
 - OS: 15.6

**Additional context**
it seems that the homepage is shown due to the error. Headline and some tabs are shown. I haven't seen landscape on electricitymaps on iPhone before. (doesn't make any sense if you ask me)

**Comment by guerda** [comment]
Have a look at #4521, it looks like this is the same issue.

**Comment by VIKTORVAV99** [comment]
Closing this as it seem to have been resolved!
