### ISSUE TITLE
Sun layer: Use a GPU-based gaussian blur (CSS / webgl) instead of CPU-based

### ISSUE THREAD

**Issue by corradio** [electricitymap/electricitymap-contrib#923]
Another idea is to use `createRadialGradient` to speed up the canvas drawing time.

**Comment by corradio** [comment]
CSS blur filter not supported in IE11

**Comment by Kongkille** [comment]
This seems like a good potential improvements, however since no ones has looked at it in a while, I am closing this issue. We can pick it up again, if we run into performance issues with the current sun layer :)
