### ISSUE TITLE
Add Belarus BY

### ISSUE THREAD

**Issue by alixunderplatz** [electricitymap/electricitymap-contrib#934]
After user @admetny has opened a pull request #931 with Belarusian capacities, I was curious and started looking for some more information.

Seems like only the **system load** for Belarus is available as image (useless for now) on the website of its grid operator:
http://www.odu.by/
![image](https://user-images.githubusercontent.com/25743609/34166454-3ebdcf7c-e4df-11e7-968a-1ca5df3880ca.png)

There is another interesting website http://operby.com/sejchas-v-oes
The authors seems to be two dispatchers of grid operators! The site publishes all kinds of technical articles and information about how the grid works etc.
These people also appear to have a related and quite active twitter account: https://twitter.com/operby

@corradio Maybe we can ask them via twitter, whether the information we need is published somewhere or if there is a way it could be published in the future?!

**Comment by corradio** [comment]
Yes go ahead!

**Comment by admetny** [comment]
Hi,

Will update README soon.

http://www.odu.by/ - is dispatcher company of Belarus electricity network. Picture you've found is auto-generated, so theoretically they are able to provide online info about consumption. I don't think that someone else is able to provide this info.

http://belenergo.by/ (http://www.energo.by) - state-owned electricity company Belenergo. Major electricity producer in Belarus (> 95% of generation).
 
"operby" is unofficial account of the Head of Press Center of Belenergo. 
It is amusingly, but he don't know English on this position.

**Comment by admetny** [comment]
Belarus has interconnections with Lithuania, Russia and Ukraine only.
BY-LT flow - probably can be taken from Lithuanian data.
BY-RU - I can try to find this real-time data but I'm not sure that it exists.
BY-UA - I see that Ukraine has real-time data with EU countries. Most probably that origin of these data a is from EU but if Ukraine has similar real-time data then it can be available for BY-UA too.

**Comment by alixunderplatz** [comment]
@admetny thank you for the additional information!

BY-RU is available here: http://br.so-ups.ru/Public/MainPage.aspx
BY-UA could be calculated using the balance between all of the documented exports and imports and the graph here: https://ua.energy/diyalnist/dyspetcherska-informatsiya/peretoky/

I suggest waiting for a possible reply from Belenergo, I'll send them a message. Maybe that's the easier way.

**Comment by admetny** [comment]
CO2:
From Belenergo site (http://www.energo.by/okon/p38.htm):
![image](https://user-images.githubusercontent.com/34665207/34226948-7903767a-e5dc-11e7-87ee-6e2e057c7f8a.png)
Obviously, kton is a mistake and have to be replaced by Mton.
2016 production is 33,566TWh almost all from gas.
Calculated Carbon Intensity is 244 gCo2eq/kWh. 
Looks very low comparing with 490 default value.

On your opinion, is it real number?

**Comment by alixunderplatz** [comment]
Privet @admetny !

For CO2 it should be Mton, definitely! 
I guess they refer to Carbon**mon**oxide CO instead, because they also list other toxic pollutants as SO2 and N2O in that table.

I found and a table with the same numbers and this on top:
"Увеличение расхода мазута, местных видов топлива привело к увеличению суммарных **выбросов загрязняющих веществ** в атмосферный воздух от стационарных источников выбросов в 2016 году на 5,5 тыс. тонн по сравнению с 2015 годом."

So I think this is only related to non-CO2-emissions.

**Comment by admetny** [comment]
I guess, you are right about CO. In this case kton is correct.

**Comment by admetny** [comment]
Don't know if it is useful or not:
![image](https://user-images.githubusercontent.com/34665207/34230478-54460dea-e5e9-11e7-813e-957975595485.png)
It contains electricity generation and heating emissions.

**Comment by systemcatch** [comment]
Any luck with contacting Belenergo guys? Maybe we could implement some of the exchanges that Belarus has with neighboring countries?

**Comment by alixunderplatz** [comment]
@systemcatch Sorry, have not yet contacted them! Will do this tomorrow and will keep you updated!

**Comment by corradio** [comment]
@alixunderplatz any news here?

**Comment by alixunderplatz** [comment]
We could now use OCR to extract the system load of Belarus. They added the value in MW to the load graph image :)
http://odu.by/upload/Potreblenie.png

![image](https://user-images.githubusercontent.com/25743609/56863634-39236d00-69b9-11e9-9b7d-a63c849e9fdd.png)

Still, no fuel types are given, but electricity is almost entirely from gas ([>97%](https://www.iea.org/statistics/?country=BELARUS&year=2016&category=Energy%20supply&indicator=ElecGenByFuel&mode=chart&dataTable=ELECTRICITYANDHEAT))

We could use
`Production = load - balance of exchanges`, but therefore we need to fix the exchanges of Russia (#1817)  first. It's probably difficult to integrate all these exchanges from three different sources into a single parser.

**Comment by poisondima** [comment]
Hi, I understand that there is no data in Belarus?

**Comment by admetny** [comment]
Hi Dima,

Things are getting worse with open data in Belarus.

No live data, but can update installed capacity if necessary (1 NPP VVER-1200 unit was commissioned and minor changes for another types).

**Comment by Kongkille** [comment]
Thanks for all the valuable information shared here! 🙌

We're closing this issue and adding to our main issue for missing countries as it doesn't currently seem possible to build a real-time parser given the data provided here.
If you find new information that might help us get it done, please comment and reopen the issue [when a parser is buildable](https://github.com/electricityMap/electricitymap-contrib/wiki/Technical-requirements-for-parser-data) :)
